import {
  ApplyPartition,
  DisconnectP2P,
  ExportDiagnostics,
  GetScenarioState,
  GetSnapshot,
  HealAll,
  IsolateNode,
  KillInstance,
  OpenRuntimeFolder,
  Preflight,
  ReconnectP2P,
  ResetAll,
  ResetInstance,
  RestartInstance,
  ResumeP2P,
  RunScenario,
  StartAll,
  StartInstance,
  StopAll,
  StopInstance,
  TriggerOfflineSync,
} from '../wailsjs/go/main/App'

export const runtimeClient = {
  getSnapshot: GetSnapshot,
  preflight: Preflight,
  startInstance: StartInstance,
  stopInstance: StopInstance,
  killInstance: KillInstance,
  restartInstance: RestartInstance,
  resetInstance: ResetInstance,
  startAll: StartAll,
  stopAll: StopAll,
  resetAll: ResetAll,
  isolateNode: IsolateNode,
  healAll: HealAll,
  applyPartition: ApplyPartition,
  disconnectP2P: DisconnectP2P,
  resumeP2P: ResumeP2P,
  reconnectP2P: ReconnectP2P,
  triggerOfflineSync: TriggerOfflineSync,
  exportDiagnostics: ExportDiagnostics,
  openRuntimeFolder: OpenRuntimeFolder,
  runScenario: RunScenario,
  getScenarioState: GetScenarioState,
}
