import {
  ApplyPartition,
  ExportDiagnostics,
  GetScenarioState,
  GetSnapshot,
  HealAll,
  IsolateNode,
  KillInstance,
  OpenInstanceLog,
  OpenRuntimeFolder,
  Preflight,
  ReadInstanceLogTail,
  RebuildDockerImage,
  ResetAll,
  ResetInstance,
  RestartInstance,
  RunScenario,
  StartAll,
  StartInstance,
  StopAll,
  StopInstance,
  TriggerOfflineSync,
} from '../wailsjs/go/main/App'

export const runtimeClient = {
  getSnapshot: GetSnapshot,
  preflight: Preflight,
  rebuildDockerImage: RebuildDockerImage,
  startInstance: StartInstance,
  stopInstance: StopInstance,
  killInstance: KillInstance,
  restartInstance: RestartInstance,
  resetInstance: ResetInstance,
  startAll: StartAll,
  stopAll: StopAll,
  resetAll: ResetAll,
  isolateNode: IsolateNode,
  healAll: HealAll,
  applyPartition: ApplyPartition,
  triggerOfflineSync: TriggerOfflineSync,
  exportDiagnostics: ExportDiagnostics,
  openRuntimeFolder: OpenRuntimeFolder,
  openInstanceLog: OpenInstanceLog,
  readInstanceLogTail: ReadInstanceLogTail,
  runScenario: RunScenario,
  getScenarioState: GetScenarioState,
}
