import {
  ApplyPartition,
  BuildGuiDemo,
  BuildHeadlessImage,
  CaptureRuntimeAsTemplate,
  ExportDiagnostics,
  GetScenarioState,
  GetSnapshot,
  HealAll,
  IsolateNode,
  OpenInstanceLog,
  OpenRuntimeFolder,
  PrepareDemoCluster,
  PreflightGUI,
  PreflightHeadless,
  ReadInstanceLogTail,
  ResetGuiLane,
  ResetHeadlessLane,
  ResetInstance,
  RestartInstance,
  RunScenario,
  SendDemoMessage,
  StartGuiLane,
  StartHeadlessLane,
  StartInstance,
  StopGuiLane,
  StopHeadlessLane,
  StopInstance,
  TriggerOfflineSync,
} from '../wailsjs/go/main/App'

export const runtimeClient = {
  getSnapshot: GetSnapshot,
  getScenarioState: GetScenarioState,
  preflightGUI: PreflightGUI,
  preflightHeadless: PreflightHeadless,
  buildGuiDemo: BuildGuiDemo,
  buildHeadlessImage: BuildHeadlessImage,
  startGuiLane: StartGuiLane,
  stopGuiLane: StopGuiLane,
  resetGuiLane: ResetGuiLane,
  startHeadlessLane: StartHeadlessLane,
  stopHeadlessLane: StopHeadlessLane,
  resetHeadlessLane: ResetHeadlessLane,
  startInstance: StartInstance,
  stopInstance: StopInstance,
  restartInstance: RestartInstance,
  resetInstance: ResetInstance,
  captureRuntimeAsTemplate: CaptureRuntimeAsTemplate,
  isolateNode: IsolateNode,
  healAll: HealAll,
  applyPartition: ApplyPartition,
  triggerOfflineSync: TriggerOfflineSync,
  exportDiagnostics: ExportDiagnostics,
  openRuntimeFolder: OpenRuntimeFolder,
  openInstanceLog: OpenInstanceLog,
  readInstanceLogTail: ReadInstanceLogTail,
  prepareDemoCluster: PrepareDemoCluster,
  sendDemoMessage: SendDemoMessage,
  runScenario: RunScenario,
}
