// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: proto/mls_service.proto

package mls_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLSCryptoService_Ping_FullMethodName                       = "/mls_service.MLSCryptoService/Ping"
	MLSCryptoService_GenerateIdentity_FullMethodName           = "/mls_service.MLSCryptoService/GenerateIdentity"
	MLSCryptoService_ExportIdentity_FullMethodName             = "/mls_service.MLSCryptoService/ExportIdentity"
	MLSCryptoService_ImportIdentity_FullMethodName             = "/mls_service.MLSCryptoService/ImportIdentity"
	MLSCryptoService_CreateGroup_FullMethodName                = "/mls_service.MLSCryptoService/CreateGroup"
	MLSCryptoService_CreateProposal_FullMethodName             = "/mls_service.MLSCryptoService/CreateProposal"
	MLSCryptoService_ProcessProposal_FullMethodName            = "/mls_service.MLSCryptoService/ProcessProposal"
	MLSCryptoService_CreateCommit_FullMethodName               = "/mls_service.MLSCryptoService/CreateCommit"
	MLSCryptoService_StageCommit_FullMethodName                = "/mls_service.MLSCryptoService/StageCommit"
	MLSCryptoService_ProcessCommit_FullMethodName              = "/mls_service.MLSCryptoService/ProcessCommit"
	MLSCryptoService_ProcessWelcome_FullMethodName             = "/mls_service.MLSCryptoService/ProcessWelcome"
	MLSCryptoService_EncryptMessage_FullMethodName             = "/mls_service.MLSCryptoService/EncryptMessage"
	MLSCryptoService_DecryptMessage_FullMethodName             = "/mls_service.MLSCryptoService/DecryptMessage"
	MLSCryptoService_ExternalJoin_FullMethodName               = "/mls_service.MLSCryptoService/ExternalJoin"
	MLSCryptoService_ExportSecret_FullMethodName               = "/mls_service.MLSCryptoService/ExportSecret"
	MLSCryptoService_GenerateKeyPackage_FullMethodName         = "/mls_service.MLSCryptoService/GenerateKeyPackage"
	MLSCryptoService_AddMembers_FullMethodName                 = "/mls_service.MLSCryptoService/AddMembers"
	MLSCryptoService_RemoveMembers_FullMethodName              = "/mls_service.MLSCryptoService/RemoveMembers"
	MLSCryptoService_HasMember_FullMethodName                  = "/mls_service.MLSCryptoService/HasMember"
	MLSCryptoService_ListMemberIdentities_FullMethodName       = "/mls_service.MLSCryptoService/ListMemberIdentities"
	MLSCryptoService_ExportGroupInfo_FullMethodName            = "/mls_service.MLSCryptoService/ExportGroupInfo"
	MLSCryptoService_LoadGroup_FullMethodName                  = "/mls_service.MLSCryptoService/LoadGroup"
	MLSCryptoService_GetGroupMetadata_FullMethodName           = "/mls_service.MLSCryptoService/GetGroupMetadata"
	MLSCryptoService_EncryptMessageCached_FullMethodName       = "/mls_service.MLSCryptoService/EncryptMessageCached"
	MLSCryptoService_DecryptMessageCached_FullMethodName       = "/mls_service.MLSCryptoService/DecryptMessageCached"
	MLSCryptoService_CreateUpdateCommitCached_FullMethodName   = "/mls_service.MLSCryptoService/CreateUpdateCommitCached"
	MLSCryptoService_ProcessCommitCached_FullMethodName        = "/mls_service.MLSCryptoService/ProcessCommitCached"
	MLSCryptoService_ExportSecretCached_FullMethodName         = "/mls_service.MLSCryptoService/ExportSecretCached"
	MLSCryptoService_ExportGroupStateCheckpoint_FullMethodName = "/mls_service.MLSCryptoService/ExportGroupStateCheckpoint"
	MLSCryptoService_UnloadGroup_FullMethodName                = "/mls_service.MLSCryptoService/UnloadGroup"
	MLSCryptoService_CreateGroupAndLoad_FullMethodName         = "/mls_service.MLSCryptoService/CreateGroupAndLoad"
	MLSCryptoService_CreateProposalCached_FullMethodName       = "/mls_service.MLSCryptoService/CreateProposalCached"
	MLSCryptoService_ProcessProposalCached_FullMethodName      = "/mls_service.MLSCryptoService/ProcessProposalCached"
	MLSCryptoService_CreateCommitCached_FullMethodName         = "/mls_service.MLSCryptoService/CreateCommitCached"
	MLSCryptoService_StageCommitCached_FullMethodName          = "/mls_service.MLSCryptoService/StageCommitCached"
	MLSCryptoService_AddMembersCached_FullMethodName           = "/mls_service.MLSCryptoService/AddMembersCached"
	MLSCryptoService_RemoveMembersCached_FullMethodName        = "/mls_service.MLSCryptoService/RemoveMembersCached"
	MLSCryptoService_HasMemberCached_FullMethodName            = "/mls_service.MLSCryptoService/HasMemberCached"
	MLSCryptoService_ListMemberIdentitiesCached_FullMethodName = "/mls_service.MLSCryptoService/ListMemberIdentitiesCached"
	MLSCryptoService_ExportGroupInfoCached_FullMethodName      = "/mls_service.MLSCryptoService/ExportGroupInfoCached"
	MLSCryptoService_ProcessWelcomeAndLoad_FullMethodName      = "/mls_service.MLSCryptoService/ProcessWelcomeAndLoad"
	MLSCryptoService_ExternalJoinAndLoad_FullMethodName        = "/mls_service.MLSCryptoService/ExternalJoinAndLoad"
)

// MLSCryptoServiceClient is the client API for MLSCryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MLSCryptoServiceClient interface {
	// ── Phase 2: Identity ──
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	GenerateIdentity(ctx context.Context, in *GenerateIdentityRequest, opts ...grpc.CallOption) (*GenerateIdentityResponse, error)
	ExportIdentity(ctx context.Context, in *ExportIdentityRequest, opts ...grpc.CallOption) (*ExportIdentityResponse, error)
	ImportIdentity(ctx context.Context, in *ImportIdentityRequest, opts ...grpc.CallOption) (*ImportIdentityResponse, error)
	// ── Phase 4: Group Operations ──
	CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error)
	CreateProposal(ctx context.Context, in *CreateProposalRequest, opts ...grpc.CallOption) (*CreateProposalResponse, error)
	ProcessProposal(ctx context.Context, in *ProcessProposalRequest, opts ...grpc.CallOption) (*ProcessProposalResponse, error)
	CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error)
	StageCommit(ctx context.Context, in *StageCommitRequest, opts ...grpc.CallOption) (*StageCommitResponse, error)
	ProcessCommit(ctx context.Context, in *ProcessCommitRequest, opts ...grpc.CallOption) (*ProcessCommitResponse, error)
	ProcessWelcome(ctx context.Context, in *ProcessWelcomeRequest, opts ...grpc.CallOption) (*ProcessWelcomeResponse, error)
	EncryptMessage(ctx context.Context, in *EncryptMessageRequest, opts ...grpc.CallOption) (*EncryptMessageResponse, error)
	DecryptMessage(ctx context.Context, in *DecryptMessageRequest, opts ...grpc.CallOption) (*DecryptMessageResponse, error)
	ExternalJoin(ctx context.Context, in *ExternalJoinRequest, opts ...grpc.CallOption) (*ExternalJoinResponse, error)
	ExportSecret(ctx context.Context, in *ExportSecretRequest, opts ...grpc.CallOption) (*ExportSecretResponse, error)
	// Phase 4.1 — Add member / KeyPackage lifecycle
	GenerateKeyPackage(ctx context.Context, in *GenerateKeyPackageRequest, opts ...grpc.CallOption) (*GenerateKeyPackageResponse, error)
	AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*AddMembersResponse, error)
	// Phase 6 — Group lifecycle: remove members. Targets are matched by
	// BasicCredential identity bytes (peer ID raw bytes). The Welcome field in
	// the response is empty for pure remove operations.
	RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error)
	// Query whether the given BasicCredential identity bytes are still a member
	// of the provided group_state. Used by Go coordinator to detect if local
	// node has been removed after applying a commit.
	HasMember(ctx context.Context, in *HasMemberRequest, opts ...grpc.CallOption) (*HasMemberResponse, error)
	// Enumerate every BasicCredential identity currently sitting on a leaf of
	// the MLS tree. Used by the Go runtime after JoinGroupWithWelcome (and on
	// every GetGroupMembers refresh) to reconstruct the full roster directly
	// from cryptographic ground truth, independent of which node sent the
	// Welcome. Order matches the leaf-index iteration order returned by the
	// OpenMLS group; the response is empty when group_state is uninitialized.
	ListMemberIdentities(ctx context.Context, in *ListMemberIdentitiesRequest, opts ...grpc.CallOption) (*ListMemberIdentitiesResponse, error)
	// Phase 4.5 — Fork healing: winning branch exports its current GroupInfo so a
	// losing-branch peer can re-join via ExternalJoin. The exported MlsMessage is
	// TLS-serialized and contains the RatchetTree extension when with_ratchet_tree=true.
	ExportGroupInfo(ctx context.Context, in *ExportGroupInfoRequest, opts ...grpc.CallOption) (*ExportGroupInfoResponse, error)
	// Phase A optimization research — hot-cache sidecar benchmark path.
	// These RPCs are additive and do not replace the production stateless RPCs.
	LoadGroup(ctx context.Context, in *LoadGroupRequest, opts ...grpc.CallOption) (*LoadGroupResponse, error)
	GetGroupMetadata(ctx context.Context, in *GetGroupMetadataRequest, opts ...grpc.CallOption) (*GetGroupMetadataResponse, error)
	EncryptMessageCached(ctx context.Context, in *EncryptMessageCachedRequest, opts ...grpc.CallOption) (*EncryptMessageCachedResponse, error)
	DecryptMessageCached(ctx context.Context, in *DecryptMessageCachedRequest, opts ...grpc.CallOption) (*DecryptMessageCachedResponse, error)
	CreateUpdateCommitCached(ctx context.Context, in *CreateUpdateCommitCachedRequest, opts ...grpc.CallOption) (*CreateUpdateCommitCachedResponse, error)
	ProcessCommitCached(ctx context.Context, in *ProcessCommitCachedRequest, opts ...grpc.CallOption) (*ProcessCommitCachedResponse, error)
	ExportSecretCached(ctx context.Context, in *ExportSecretCachedRequest, opts ...grpc.CallOption) (*ExportSecretCachedResponse, error)
	ExportGroupStateCheckpoint(ctx context.Context, in *ExportGroupStateCheckpointRequest, opts ...grpc.CallOption) (*ExportGroupStateCheckpointResponse, error)
	UnloadGroup(ctx context.Context, in *UnloadGroupRequest, opts ...grpc.CallOption) (*UnloadGroupResponse, error)
	// Phase B optimization — stateful cached operations for production path.
	// These RPCs use the RuntimeCache to avoid serializing/deserializing group
	// state on every call. The Go adapter calls LoadGroup once, then uses
	// cached RPCs for subsequent operations. Only ExportGroupStateCheckpoint
	// serializes state (once per mutation, for SQLite persistence).
	CreateGroupAndLoad(ctx context.Context, in *CreateGroupAndLoadRequest, opts ...grpc.CallOption) (*CreateGroupAndLoadResponse, error)
	CreateProposalCached(ctx context.Context, in *CreateProposalCachedRequest, opts ...grpc.CallOption) (*CreateProposalCachedResponse, error)
	ProcessProposalCached(ctx context.Context, in *ProcessProposalCachedRequest, opts ...grpc.CallOption) (*ProcessProposalCachedResponse, error)
	CreateCommitCached(ctx context.Context, in *CreateCommitCachedRequest, opts ...grpc.CallOption) (*CreateCommitCachedResponse, error)
	StageCommitCached(ctx context.Context, in *StageCommitCachedRequest, opts ...grpc.CallOption) (*StageCommitCachedResponse, error)
	AddMembersCached(ctx context.Context, in *AddMembersCachedRequest, opts ...grpc.CallOption) (*AddMembersCachedResponse, error)
	RemoveMembersCached(ctx context.Context, in *RemoveMembersCachedRequest, opts ...grpc.CallOption) (*RemoveMembersCachedResponse, error)
	HasMemberCached(ctx context.Context, in *HasMemberCachedRequest, opts ...grpc.CallOption) (*HasMemberCachedResponse, error)
	ListMemberIdentitiesCached(ctx context.Context, in *ListMemberIdentitiesCachedRequest, opts ...grpc.CallOption) (*ListMemberIdentitiesCachedResponse, error)
	ExportGroupInfoCached(ctx context.Context, in *ExportGroupInfoCachedRequest, opts ...grpc.CallOption) (*ExportGroupInfoCachedResponse, error)
	ProcessWelcomeAndLoad(ctx context.Context, in *ProcessWelcomeAndLoadRequest, opts ...grpc.CallOption) (*ProcessWelcomeAndLoadResponse, error)
	ExternalJoinAndLoad(ctx context.Context, in *ExternalJoinAndLoadRequest, opts ...grpc.CallOption) (*ExternalJoinAndLoadResponse, error)
}

type mLSCryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLSCryptoServiceClient(cc grpc.ClientConnInterface) MLSCryptoServiceClient {
	return &mLSCryptoServiceClient{cc}
}

func (c *mLSCryptoServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) GenerateIdentity(ctx context.Context, in *GenerateIdentityRequest, opts ...grpc.CallOption) (*GenerateIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_GenerateIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportIdentity(ctx context.Context, in *ExportIdentityRequest, opts ...grpc.CallOption) (*ExportIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ImportIdentity(ctx context.Context, in *ImportIdentityRequest, opts ...grpc.CallOption) (*ImportIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ImportIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateGroup(ctx context.Context, in *CreateGroupRequest, opts ...grpc.CallOption) (*CreateGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateProposal(ctx context.Context, in *CreateProposalRequest, opts ...grpc.CallOption) (*CreateProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProposalResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessProposal(ctx context.Context, in *ProcessProposalRequest, opts ...grpc.CallOption) (*ProcessProposalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessProposalResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessProposal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateCommit(ctx context.Context, in *CreateCommitRequest, opts ...grpc.CallOption) (*CreateCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommitResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) StageCommit(ctx context.Context, in *StageCommitRequest, opts ...grpc.CallOption) (*StageCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageCommitResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_StageCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessCommit(ctx context.Context, in *ProcessCommitRequest, opts ...grpc.CallOption) (*ProcessCommitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessCommitResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessCommit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessWelcome(ctx context.Context, in *ProcessWelcomeRequest, opts ...grpc.CallOption) (*ProcessWelcomeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWelcomeResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessWelcome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) EncryptMessage(ctx context.Context, in *EncryptMessageRequest, opts ...grpc.CallOption) (*EncryptMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptMessageResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_EncryptMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) DecryptMessage(ctx context.Context, in *DecryptMessageRequest, opts ...grpc.CallOption) (*DecryptMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptMessageResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_DecryptMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExternalJoin(ctx context.Context, in *ExternalJoinRequest, opts ...grpc.CallOption) (*ExternalJoinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalJoinResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExternalJoin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportSecret(ctx context.Context, in *ExportSecretRequest, opts ...grpc.CallOption) (*ExportSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSecretResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) GenerateKeyPackage(ctx context.Context, in *GenerateKeyPackageRequest, opts ...grpc.CallOption) (*GenerateKeyPackageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKeyPackageResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_GenerateKeyPackage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) AddMembers(ctx context.Context, in *AddMembersRequest, opts ...grpc.CallOption) (*AddMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMembersResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_AddMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) RemoveMembers(ctx context.Context, in *RemoveMembersRequest, opts ...grpc.CallOption) (*RemoveMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMembersResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_RemoveMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) HasMember(ctx context.Context, in *HasMemberRequest, opts ...grpc.CallOption) (*HasMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasMemberResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_HasMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ListMemberIdentities(ctx context.Context, in *ListMemberIdentitiesRequest, opts ...grpc.CallOption) (*ListMemberIdentitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberIdentitiesResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ListMemberIdentities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportGroupInfo(ctx context.Context, in *ExportGroupInfoRequest, opts ...grpc.CallOption) (*ExportGroupInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGroupInfoResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportGroupInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) LoadGroup(ctx context.Context, in *LoadGroupRequest, opts ...grpc.CallOption) (*LoadGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoadGroupResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_LoadGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) GetGroupMetadata(ctx context.Context, in *GetGroupMetadataRequest, opts ...grpc.CallOption) (*GetGroupMetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGroupMetadataResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_GetGroupMetadata_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) EncryptMessageCached(ctx context.Context, in *EncryptMessageCachedRequest, opts ...grpc.CallOption) (*EncryptMessageCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptMessageCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_EncryptMessageCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) DecryptMessageCached(ctx context.Context, in *DecryptMessageCachedRequest, opts ...grpc.CallOption) (*DecryptMessageCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptMessageCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_DecryptMessageCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateUpdateCommitCached(ctx context.Context, in *CreateUpdateCommitCachedRequest, opts ...grpc.CallOption) (*CreateUpdateCommitCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateUpdateCommitCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateUpdateCommitCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessCommitCached(ctx context.Context, in *ProcessCommitCachedRequest, opts ...grpc.CallOption) (*ProcessCommitCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessCommitCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessCommitCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportSecretCached(ctx context.Context, in *ExportSecretCachedRequest, opts ...grpc.CallOption) (*ExportSecretCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportSecretCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportSecretCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportGroupStateCheckpoint(ctx context.Context, in *ExportGroupStateCheckpointRequest, opts ...grpc.CallOption) (*ExportGroupStateCheckpointResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGroupStateCheckpointResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportGroupStateCheckpoint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) UnloadGroup(ctx context.Context, in *UnloadGroupRequest, opts ...grpc.CallOption) (*UnloadGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnloadGroupResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_UnloadGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateGroupAndLoad(ctx context.Context, in *CreateGroupAndLoadRequest, opts ...grpc.CallOption) (*CreateGroupAndLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateGroupAndLoadResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateGroupAndLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateProposalCached(ctx context.Context, in *CreateProposalCachedRequest, opts ...grpc.CallOption) (*CreateProposalCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProposalCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateProposalCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessProposalCached(ctx context.Context, in *ProcessProposalCachedRequest, opts ...grpc.CallOption) (*ProcessProposalCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessProposalCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessProposalCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) CreateCommitCached(ctx context.Context, in *CreateCommitCachedRequest, opts ...grpc.CallOption) (*CreateCommitCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCommitCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_CreateCommitCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) StageCommitCached(ctx context.Context, in *StageCommitCachedRequest, opts ...grpc.CallOption) (*StageCommitCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StageCommitCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_StageCommitCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) AddMembersCached(ctx context.Context, in *AddMembersCachedRequest, opts ...grpc.CallOption) (*AddMembersCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddMembersCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_AddMembersCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) RemoveMembersCached(ctx context.Context, in *RemoveMembersCachedRequest, opts ...grpc.CallOption) (*RemoveMembersCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveMembersCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_RemoveMembersCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) HasMemberCached(ctx context.Context, in *HasMemberCachedRequest, opts ...grpc.CallOption) (*HasMemberCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HasMemberCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_HasMemberCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ListMemberIdentitiesCached(ctx context.Context, in *ListMemberIdentitiesCachedRequest, opts ...grpc.CallOption) (*ListMemberIdentitiesCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberIdentitiesCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ListMemberIdentitiesCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportGroupInfoCached(ctx context.Context, in *ExportGroupInfoCachedRequest, opts ...grpc.CallOption) (*ExportGroupInfoCachedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportGroupInfoCachedResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportGroupInfoCached_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ProcessWelcomeAndLoad(ctx context.Context, in *ProcessWelcomeAndLoadRequest, opts ...grpc.CallOption) (*ProcessWelcomeAndLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessWelcomeAndLoadResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ProcessWelcomeAndLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExternalJoinAndLoad(ctx context.Context, in *ExternalJoinAndLoadRequest, opts ...grpc.CallOption) (*ExternalJoinAndLoadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExternalJoinAndLoadResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExternalJoinAndLoad_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLSCryptoServiceServer is the server API for MLSCryptoService service.
// All implementations must embed UnimplementedMLSCryptoServiceServer
// for forward compatibility.
type MLSCryptoServiceServer interface {
	// ── Phase 2: Identity ──
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	GenerateIdentity(context.Context, *GenerateIdentityRequest) (*GenerateIdentityResponse, error)
	ExportIdentity(context.Context, *ExportIdentityRequest) (*ExportIdentityResponse, error)
	ImportIdentity(context.Context, *ImportIdentityRequest) (*ImportIdentityResponse, error)
	// ── Phase 4: Group Operations ──
	CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error)
	CreateProposal(context.Context, *CreateProposalRequest) (*CreateProposalResponse, error)
	ProcessProposal(context.Context, *ProcessProposalRequest) (*ProcessProposalResponse, error)
	CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error)
	StageCommit(context.Context, *StageCommitRequest) (*StageCommitResponse, error)
	ProcessCommit(context.Context, *ProcessCommitRequest) (*ProcessCommitResponse, error)
	ProcessWelcome(context.Context, *ProcessWelcomeRequest) (*ProcessWelcomeResponse, error)
	EncryptMessage(context.Context, *EncryptMessageRequest) (*EncryptMessageResponse, error)
	DecryptMessage(context.Context, *DecryptMessageRequest) (*DecryptMessageResponse, error)
	ExternalJoin(context.Context, *ExternalJoinRequest) (*ExternalJoinResponse, error)
	ExportSecret(context.Context, *ExportSecretRequest) (*ExportSecretResponse, error)
	// Phase 4.1 — Add member / KeyPackage lifecycle
	GenerateKeyPackage(context.Context, *GenerateKeyPackageRequest) (*GenerateKeyPackageResponse, error)
	AddMembers(context.Context, *AddMembersRequest) (*AddMembersResponse, error)
	// Phase 6 — Group lifecycle: remove members. Targets are matched by
	// BasicCredential identity bytes (peer ID raw bytes). The Welcome field in
	// the response is empty for pure remove operations.
	RemoveMembers(context.Context, *RemoveMembersRequest) (*RemoveMembersResponse, error)
	// Query whether the given BasicCredential identity bytes are still a member
	// of the provided group_state. Used by Go coordinator to detect if local
	// node has been removed after applying a commit.
	HasMember(context.Context, *HasMemberRequest) (*HasMemberResponse, error)
	// Enumerate every BasicCredential identity currently sitting on a leaf of
	// the MLS tree. Used by the Go runtime after JoinGroupWithWelcome (and on
	// every GetGroupMembers refresh) to reconstruct the full roster directly
	// from cryptographic ground truth, independent of which node sent the
	// Welcome. Order matches the leaf-index iteration order returned by the
	// OpenMLS group; the response is empty when group_state is uninitialized.
	ListMemberIdentities(context.Context, *ListMemberIdentitiesRequest) (*ListMemberIdentitiesResponse, error)
	// Phase 4.5 — Fork healing: winning branch exports its current GroupInfo so a
	// losing-branch peer can re-join via ExternalJoin. The exported MlsMessage is
	// TLS-serialized and contains the RatchetTree extension when with_ratchet_tree=true.
	ExportGroupInfo(context.Context, *ExportGroupInfoRequest) (*ExportGroupInfoResponse, error)
	// Phase A optimization research — hot-cache sidecar benchmark path.
	// These RPCs are additive and do not replace the production stateless RPCs.
	LoadGroup(context.Context, *LoadGroupRequest) (*LoadGroupResponse, error)
	GetGroupMetadata(context.Context, *GetGroupMetadataRequest) (*GetGroupMetadataResponse, error)
	EncryptMessageCached(context.Context, *EncryptMessageCachedRequest) (*EncryptMessageCachedResponse, error)
	DecryptMessageCached(context.Context, *DecryptMessageCachedRequest) (*DecryptMessageCachedResponse, error)
	CreateUpdateCommitCached(context.Context, *CreateUpdateCommitCachedRequest) (*CreateUpdateCommitCachedResponse, error)
	ProcessCommitCached(context.Context, *ProcessCommitCachedRequest) (*ProcessCommitCachedResponse, error)
	ExportSecretCached(context.Context, *ExportSecretCachedRequest) (*ExportSecretCachedResponse, error)
	ExportGroupStateCheckpoint(context.Context, *ExportGroupStateCheckpointRequest) (*ExportGroupStateCheckpointResponse, error)
	UnloadGroup(context.Context, *UnloadGroupRequest) (*UnloadGroupResponse, error)
	// Phase B optimization — stateful cached operations for production path.
	// These RPCs use the RuntimeCache to avoid serializing/deserializing group
	// state on every call. The Go adapter calls LoadGroup once, then uses
	// cached RPCs for subsequent operations. Only ExportGroupStateCheckpoint
	// serializes state (once per mutation, for SQLite persistence).
	CreateGroupAndLoad(context.Context, *CreateGroupAndLoadRequest) (*CreateGroupAndLoadResponse, error)
	CreateProposalCached(context.Context, *CreateProposalCachedRequest) (*CreateProposalCachedResponse, error)
	ProcessProposalCached(context.Context, *ProcessProposalCachedRequest) (*ProcessProposalCachedResponse, error)
	CreateCommitCached(context.Context, *CreateCommitCachedRequest) (*CreateCommitCachedResponse, error)
	StageCommitCached(context.Context, *StageCommitCachedRequest) (*StageCommitCachedResponse, error)
	AddMembersCached(context.Context, *AddMembersCachedRequest) (*AddMembersCachedResponse, error)
	RemoveMembersCached(context.Context, *RemoveMembersCachedRequest) (*RemoveMembersCachedResponse, error)
	HasMemberCached(context.Context, *HasMemberCachedRequest) (*HasMemberCachedResponse, error)
	ListMemberIdentitiesCached(context.Context, *ListMemberIdentitiesCachedRequest) (*ListMemberIdentitiesCachedResponse, error)
	ExportGroupInfoCached(context.Context, *ExportGroupInfoCachedRequest) (*ExportGroupInfoCachedResponse, error)
	ProcessWelcomeAndLoad(context.Context, *ProcessWelcomeAndLoadRequest) (*ProcessWelcomeAndLoadResponse, error)
	ExternalJoinAndLoad(context.Context, *ExternalJoinAndLoadRequest) (*ExternalJoinAndLoadResponse, error)
	mustEmbedUnimplementedMLSCryptoServiceServer()
}

// UnimplementedMLSCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLSCryptoServiceServer struct{}

func (UnimplementedMLSCryptoServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMLSCryptoServiceServer) GenerateIdentity(context.Context, *GenerateIdentityRequest) (*GenerateIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportIdentity(context.Context, *ExportIdentityRequest) (*ExportIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ImportIdentity(context.Context, *ImportIdentityRequest) (*ImportIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateGroup(context.Context, *CreateGroupRequest) (*CreateGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroup not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateProposal(context.Context, *CreateProposalRequest) (*CreateProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProposal not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessProposal(context.Context, *ProcessProposalRequest) (*ProcessProposalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessProposal not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateCommit(context.Context, *CreateCommitRequest) (*CreateCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommit not implemented")
}
func (UnimplementedMLSCryptoServiceServer) StageCommit(context.Context, *StageCommitRequest) (*StageCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageCommit not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessCommit(context.Context, *ProcessCommitRequest) (*ProcessCommitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessCommit not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessWelcome(context.Context, *ProcessWelcomeRequest) (*ProcessWelcomeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWelcome not implemented")
}
func (UnimplementedMLSCryptoServiceServer) EncryptMessage(context.Context, *EncryptMessageRequest) (*EncryptMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptMessage not implemented")
}
func (UnimplementedMLSCryptoServiceServer) DecryptMessage(context.Context, *DecryptMessageRequest) (*DecryptMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptMessage not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExternalJoin(context.Context, *ExternalJoinRequest) (*ExternalJoinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExternalJoin not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportSecret(context.Context, *ExportSecretRequest) (*ExportSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSecret not implemented")
}
func (UnimplementedMLSCryptoServiceServer) GenerateKeyPackage(context.Context, *GenerateKeyPackageRequest) (*GenerateKeyPackageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateKeyPackage not implemented")
}
func (UnimplementedMLSCryptoServiceServer) AddMembers(context.Context, *AddMembersRequest) (*AddMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMembers not implemented")
}
func (UnimplementedMLSCryptoServiceServer) RemoveMembers(context.Context, *RemoveMembersRequest) (*RemoveMembersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMembers not implemented")
}
func (UnimplementedMLSCryptoServiceServer) HasMember(context.Context, *HasMemberRequest) (*HasMemberResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasMember not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ListMemberIdentities(context.Context, *ListMemberIdentitiesRequest) (*ListMemberIdentitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberIdentities not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportGroupInfo(context.Context, *ExportGroupInfoRequest) (*ExportGroupInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportGroupInfo not implemented")
}
func (UnimplementedMLSCryptoServiceServer) LoadGroup(context.Context, *LoadGroupRequest) (*LoadGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method LoadGroup not implemented")
}
func (UnimplementedMLSCryptoServiceServer) GetGroupMetadata(context.Context, *GetGroupMetadataRequest) (*GetGroupMetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGroupMetadata not implemented")
}
func (UnimplementedMLSCryptoServiceServer) EncryptMessageCached(context.Context, *EncryptMessageCachedRequest) (*EncryptMessageCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EncryptMessageCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) DecryptMessageCached(context.Context, *DecryptMessageCachedRequest) (*DecryptMessageCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DecryptMessageCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateUpdateCommitCached(context.Context, *CreateUpdateCommitCachedRequest) (*CreateUpdateCommitCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateUpdateCommitCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessCommitCached(context.Context, *ProcessCommitCachedRequest) (*ProcessCommitCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessCommitCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportSecretCached(context.Context, *ExportSecretCachedRequest) (*ExportSecretCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportSecretCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportGroupStateCheckpoint(context.Context, *ExportGroupStateCheckpointRequest) (*ExportGroupStateCheckpointResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportGroupStateCheckpoint not implemented")
}
func (UnimplementedMLSCryptoServiceServer) UnloadGroup(context.Context, *UnloadGroupRequest) (*UnloadGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnloadGroup not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateGroupAndLoad(context.Context, *CreateGroupAndLoadRequest) (*CreateGroupAndLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateGroupAndLoad not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateProposalCached(context.Context, *CreateProposalCachedRequest) (*CreateProposalCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProposalCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessProposalCached(context.Context, *ProcessProposalCachedRequest) (*ProcessProposalCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessProposalCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) CreateCommitCached(context.Context, *CreateCommitCachedRequest) (*CreateCommitCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCommitCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) StageCommitCached(context.Context, *StageCommitCachedRequest) (*StageCommitCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StageCommitCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) AddMembersCached(context.Context, *AddMembersCachedRequest) (*AddMembersCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddMembersCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) RemoveMembersCached(context.Context, *RemoveMembersCachedRequest) (*RemoveMembersCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveMembersCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) HasMemberCached(context.Context, *HasMemberCachedRequest) (*HasMemberCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HasMemberCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ListMemberIdentitiesCached(context.Context, *ListMemberIdentitiesCachedRequest) (*ListMemberIdentitiesCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberIdentitiesCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportGroupInfoCached(context.Context, *ExportGroupInfoCachedRequest) (*ExportGroupInfoCachedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportGroupInfoCached not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ProcessWelcomeAndLoad(context.Context, *ProcessWelcomeAndLoadRequest) (*ProcessWelcomeAndLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessWelcomeAndLoad not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExternalJoinAndLoad(context.Context, *ExternalJoinAndLoadRequest) (*ExternalJoinAndLoadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExternalJoinAndLoad not implemented")
}
func (UnimplementedMLSCryptoServiceServer) mustEmbedUnimplementedMLSCryptoServiceServer() {}
func (UnimplementedMLSCryptoServiceServer) testEmbeddedByValue()                          {}

// UnsafeMLSCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLSCryptoServiceServer will
// result in compilation errors.
type UnsafeMLSCryptoServiceServer interface {
	mustEmbedUnimplementedMLSCryptoServiceServer()
}

func RegisterMLSCryptoServiceServer(s grpc.ServiceRegistrar, srv MLSCryptoServiceServer) {
	// If the following call panics, it indicates UnimplementedMLSCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLSCryptoService_ServiceDesc, srv)
}

func _MLSCryptoService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_GenerateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).GenerateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_GenerateIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).GenerateIdentity(ctx, req.(*GenerateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportIdentity(ctx, req.(*ExportIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ImportIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ImportIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ImportIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ImportIdentity(ctx, req.(*ImportIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateGroup(ctx, req.(*CreateGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateProposal(ctx, req.(*CreateProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessProposal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessProposalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessProposal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessProposal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessProposal(ctx, req.(*ProcessProposalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateCommit(ctx, req.(*CreateCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_StageCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).StageCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_StageCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).StageCommit(ctx, req.(*StageCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessCommit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCommitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessCommit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessCommit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessCommit(ctx, req.(*ProcessCommitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessWelcome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWelcomeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessWelcome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessWelcome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessWelcome(ctx, req.(*ProcessWelcomeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_EncryptMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).EncryptMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_EncryptMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).EncryptMessage(ctx, req.(*EncryptMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_DecryptMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).DecryptMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_DecryptMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).DecryptMessage(ctx, req.(*DecryptMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExternalJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExternalJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExternalJoin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExternalJoin(ctx, req.(*ExternalJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportSecret(ctx, req.(*ExportSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_GenerateKeyPackage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKeyPackageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).GenerateKeyPackage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_GenerateKeyPackage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).GenerateKeyPackage(ctx, req.(*GenerateKeyPackageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_AddMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).AddMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_AddMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).AddMembers(ctx, req.(*AddMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_RemoveMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).RemoveMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_RemoveMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).RemoveMembers(ctx, req.(*RemoveMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_HasMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).HasMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_HasMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).HasMember(ctx, req.(*HasMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ListMemberIdentities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberIdentitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ListMemberIdentities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ListMemberIdentities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ListMemberIdentities(ctx, req.(*ListMemberIdentitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportGroupInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGroupInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportGroupInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportGroupInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportGroupInfo(ctx, req.(*ExportGroupInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_LoadGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).LoadGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_LoadGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).LoadGroup(ctx, req.(*LoadGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_GetGroupMetadata_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGroupMetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).GetGroupMetadata(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_GetGroupMetadata_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).GetGroupMetadata(ctx, req.(*GetGroupMetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_EncryptMessageCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptMessageCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).EncryptMessageCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_EncryptMessageCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).EncryptMessageCached(ctx, req.(*EncryptMessageCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_DecryptMessageCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptMessageCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).DecryptMessageCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_DecryptMessageCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).DecryptMessageCached(ctx, req.(*DecryptMessageCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateUpdateCommitCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUpdateCommitCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateUpdateCommitCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateUpdateCommitCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateUpdateCommitCached(ctx, req.(*CreateUpdateCommitCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessCommitCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessCommitCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessCommitCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessCommitCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessCommitCached(ctx, req.(*ProcessCommitCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportSecretCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportSecretCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportSecretCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportSecretCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportSecretCached(ctx, req.(*ExportSecretCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportGroupStateCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGroupStateCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportGroupStateCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportGroupStateCheckpoint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportGroupStateCheckpoint(ctx, req.(*ExportGroupStateCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_UnloadGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).UnloadGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_UnloadGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).UnloadGroup(ctx, req.(*UnloadGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateGroupAndLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateGroupAndLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateGroupAndLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateGroupAndLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateGroupAndLoad(ctx, req.(*CreateGroupAndLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateProposalCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProposalCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateProposalCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateProposalCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateProposalCached(ctx, req.(*CreateProposalCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessProposalCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessProposalCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessProposalCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessProposalCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessProposalCached(ctx, req.(*ProcessProposalCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_CreateCommitCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCommitCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).CreateCommitCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_CreateCommitCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).CreateCommitCached(ctx, req.(*CreateCommitCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_StageCommitCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StageCommitCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).StageCommitCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_StageCommitCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).StageCommitCached(ctx, req.(*StageCommitCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_AddMembersCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMembersCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).AddMembersCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_AddMembersCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).AddMembersCached(ctx, req.(*AddMembersCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_RemoveMembersCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveMembersCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).RemoveMembersCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_RemoveMembersCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).RemoveMembersCached(ctx, req.(*RemoveMembersCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_HasMemberCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HasMemberCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).HasMemberCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_HasMemberCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).HasMemberCached(ctx, req.(*HasMemberCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ListMemberIdentitiesCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberIdentitiesCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ListMemberIdentitiesCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ListMemberIdentitiesCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ListMemberIdentitiesCached(ctx, req.(*ListMemberIdentitiesCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportGroupInfoCached_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportGroupInfoCachedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportGroupInfoCached(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportGroupInfoCached_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportGroupInfoCached(ctx, req.(*ExportGroupInfoCachedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ProcessWelcomeAndLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessWelcomeAndLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ProcessWelcomeAndLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ProcessWelcomeAndLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ProcessWelcomeAndLoad(ctx, req.(*ProcessWelcomeAndLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExternalJoinAndLoad_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExternalJoinAndLoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExternalJoinAndLoad(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExternalJoinAndLoad_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExternalJoinAndLoad(ctx, req.(*ExternalJoinAndLoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLSCryptoService_ServiceDesc is the grpc.ServiceDesc for MLSCryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLSCryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mls_service.MLSCryptoService",
	HandlerType: (*MLSCryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _MLSCryptoService_Ping_Handler,
		},
		{
			MethodName: "GenerateIdentity",
			Handler:    _MLSCryptoService_GenerateIdentity_Handler,
		},
		{
			MethodName: "ExportIdentity",
			Handler:    _MLSCryptoService_ExportIdentity_Handler,
		},
		{
			MethodName: "ImportIdentity",
			Handler:    _MLSCryptoService_ImportIdentity_Handler,
		},
		{
			MethodName: "CreateGroup",
			Handler:    _MLSCryptoService_CreateGroup_Handler,
		},
		{
			MethodName: "CreateProposal",
			Handler:    _MLSCryptoService_CreateProposal_Handler,
		},
		{
			MethodName: "ProcessProposal",
			Handler:    _MLSCryptoService_ProcessProposal_Handler,
		},
		{
			MethodName: "CreateCommit",
			Handler:    _MLSCryptoService_CreateCommit_Handler,
		},
		{
			MethodName: "StageCommit",
			Handler:    _MLSCryptoService_StageCommit_Handler,
		},
		{
			MethodName: "ProcessCommit",
			Handler:    _MLSCryptoService_ProcessCommit_Handler,
		},
		{
			MethodName: "ProcessWelcome",
			Handler:    _MLSCryptoService_ProcessWelcome_Handler,
		},
		{
			MethodName: "EncryptMessage",
			Handler:    _MLSCryptoService_EncryptMessage_Handler,
		},
		{
			MethodName: "DecryptMessage",
			Handler:    _MLSCryptoService_DecryptMessage_Handler,
		},
		{
			MethodName: "ExternalJoin",
			Handler:    _MLSCryptoService_ExternalJoin_Handler,
		},
		{
			MethodName: "ExportSecret",
			Handler:    _MLSCryptoService_ExportSecret_Handler,
		},
		{
			MethodName: "GenerateKeyPackage",
			Handler:    _MLSCryptoService_GenerateKeyPackage_Handler,
		},
		{
			MethodName: "AddMembers",
			Handler:    _MLSCryptoService_AddMembers_Handler,
		},
		{
			MethodName: "RemoveMembers",
			Handler:    _MLSCryptoService_RemoveMembers_Handler,
		},
		{
			MethodName: "HasMember",
			Handler:    _MLSCryptoService_HasMember_Handler,
		},
		{
			MethodName: "ListMemberIdentities",
			Handler:    _MLSCryptoService_ListMemberIdentities_Handler,
		},
		{
			MethodName: "ExportGroupInfo",
			Handler:    _MLSCryptoService_ExportGroupInfo_Handler,
		},
		{
			MethodName: "LoadGroup",
			Handler:    _MLSCryptoService_LoadGroup_Handler,
		},
		{
			MethodName: "GetGroupMetadata",
			Handler:    _MLSCryptoService_GetGroupMetadata_Handler,
		},
		{
			MethodName: "EncryptMessageCached",
			Handler:    _MLSCryptoService_EncryptMessageCached_Handler,
		},
		{
			MethodName: "DecryptMessageCached",
			Handler:    _MLSCryptoService_DecryptMessageCached_Handler,
		},
		{
			MethodName: "CreateUpdateCommitCached",
			Handler:    _MLSCryptoService_CreateUpdateCommitCached_Handler,
		},
		{
			MethodName: "ProcessCommitCached",
			Handler:    _MLSCryptoService_ProcessCommitCached_Handler,
		},
		{
			MethodName: "ExportSecretCached",
			Handler:    _MLSCryptoService_ExportSecretCached_Handler,
		},
		{
			MethodName: "ExportGroupStateCheckpoint",
			Handler:    _MLSCryptoService_ExportGroupStateCheckpoint_Handler,
		},
		{
			MethodName: "UnloadGroup",
			Handler:    _MLSCryptoService_UnloadGroup_Handler,
		},
		{
			MethodName: "CreateGroupAndLoad",
			Handler:    _MLSCryptoService_CreateGroupAndLoad_Handler,
		},
		{
			MethodName: "CreateProposalCached",
			Handler:    _MLSCryptoService_CreateProposalCached_Handler,
		},
		{
			MethodName: "ProcessProposalCached",
			Handler:    _MLSCryptoService_ProcessProposalCached_Handler,
		},
		{
			MethodName: "CreateCommitCached",
			Handler:    _MLSCryptoService_CreateCommitCached_Handler,
		},
		{
			MethodName: "StageCommitCached",
			Handler:    _MLSCryptoService_StageCommitCached_Handler,
		},
		{
			MethodName: "AddMembersCached",
			Handler:    _MLSCryptoService_AddMembersCached_Handler,
		},
		{
			MethodName: "RemoveMembersCached",
			Handler:    _MLSCryptoService_RemoveMembersCached_Handler,
		},
		{
			MethodName: "HasMemberCached",
			Handler:    _MLSCryptoService_HasMemberCached_Handler,
		},
		{
			MethodName: "ListMemberIdentitiesCached",
			Handler:    _MLSCryptoService_ListMemberIdentitiesCached_Handler,
		},
		{
			MethodName: "ExportGroupInfoCached",
			Handler:    _MLSCryptoService_ExportGroupInfoCached_Handler,
		},
		{
			MethodName: "ProcessWelcomeAndLoad",
			Handler:    _MLSCryptoService_ProcessWelcomeAndLoad_Handler,
		},
		{
			MethodName: "ExternalJoinAndLoad",
			Handler:    _MLSCryptoService_ExternalJoinAndLoad_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mls_service.proto",
}
