// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.6
// source: mls_service.proto

package mls_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MLSCryptoService_GenerateIdentity_FullMethodName = "/mls_service.MLSCryptoService/GenerateIdentity"
	MLSCryptoService_ExportIdentity_FullMethodName   = "/mls_service.MLSCryptoService/ExportIdentity"
	MLSCryptoService_ImportIdentity_FullMethodName   = "/mls_service.MLSCryptoService/ImportIdentity"
	MLSCryptoService_Ping_FullMethodName             = "/mls_service.MLSCryptoService/Ping"
)

// MLSCryptoServiceClient is the client API for MLSCryptoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MLSCryptoService provides cryptographic operations using OpenMLS.
type MLSCryptoServiceClient interface {
	// Generates a new identity for the user.
	GenerateIdentity(ctx context.Context, in *GenerateIdentityRequest, opts ...grpc.CallOption) (*GenerateIdentityResponse, error)
	// Exports the current identity, typically for backup or migration.
	ExportIdentity(ctx context.Context, in *ExportIdentityRequest, opts ...grpc.CallOption) (*ExportIdentityResponse, error)
	// Imports an identity from previously exported data.
	ImportIdentity(ctx context.Context, in *ImportIdentityRequest, opts ...grpc.CallOption) (*ImportIdentityResponse, error)
	// A simple ping method to check service connectivity.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
}

type mLSCryptoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMLSCryptoServiceClient(cc grpc.ClientConnInterface) MLSCryptoServiceClient {
	return &mLSCryptoServiceClient{cc}
}

func (c *mLSCryptoServiceClient) GenerateIdentity(ctx context.Context, in *GenerateIdentityRequest, opts ...grpc.CallOption) (*GenerateIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_GenerateIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ExportIdentity(ctx context.Context, in *ExportIdentityRequest, opts ...grpc.CallOption) (*ExportIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ExportIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) ImportIdentity(ctx context.Context, in *ImportIdentityRequest, opts ...grpc.CallOption) (*ImportIdentityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportIdentityResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_ImportIdentity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mLSCryptoServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, MLSCryptoService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MLSCryptoServiceServer is the server API for MLSCryptoService service.
// All implementations must embed UnimplementedMLSCryptoServiceServer
// for forward compatibility.
//
// MLSCryptoService provides cryptographic operations using OpenMLS.
type MLSCryptoServiceServer interface {
	// Generates a new identity for the user.
	GenerateIdentity(context.Context, *GenerateIdentityRequest) (*GenerateIdentityResponse, error)
	// Exports the current identity, typically for backup or migration.
	ExportIdentity(context.Context, *ExportIdentityRequest) (*ExportIdentityResponse, error)
	// Imports an identity from previously exported data.
	ImportIdentity(context.Context, *ImportIdentityRequest) (*ImportIdentityResponse, error)
	// A simple ping method to check service connectivity.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	mustEmbedUnimplementedMLSCryptoServiceServer()
}

// UnimplementedMLSCryptoServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMLSCryptoServiceServer struct{}

func (UnimplementedMLSCryptoServiceServer) GenerateIdentity(context.Context, *GenerateIdentityRequest) (*GenerateIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ExportIdentity(context.Context, *ExportIdentityRequest) (*ExportIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExportIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) ImportIdentity(context.Context, *ImportIdentityRequest) (*ImportIdentityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportIdentity not implemented")
}
func (UnimplementedMLSCryptoServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedMLSCryptoServiceServer) mustEmbedUnimplementedMLSCryptoServiceServer() {}
func (UnimplementedMLSCryptoServiceServer) testEmbeddedByValue()                          {}

// UnsafeMLSCryptoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MLSCryptoServiceServer will
// result in compilation errors.
type UnsafeMLSCryptoServiceServer interface {
	mustEmbedUnimplementedMLSCryptoServiceServer()
}

func RegisterMLSCryptoServiceServer(s grpc.ServiceRegistrar, srv MLSCryptoServiceServer) {
	// If the following call panics, it indicates UnimplementedMLSCryptoServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MLSCryptoService_ServiceDesc, srv)
}

func _MLSCryptoService_GenerateIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).GenerateIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_GenerateIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).GenerateIdentity(ctx, req.(*GenerateIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ExportIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ExportIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ExportIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ExportIdentity(ctx, req.(*ExportIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_ImportIdentity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportIdentityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).ImportIdentity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_ImportIdentity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).ImportIdentity(ctx, req.(*ImportIdentityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MLSCryptoService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MLSCryptoServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MLSCryptoService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MLSCryptoServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MLSCryptoService_ServiceDesc is the grpc.ServiceDesc for MLSCryptoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MLSCryptoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mls_service.MLSCryptoService",
	HandlerType: (*MLSCryptoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateIdentity",
			Handler:    _MLSCryptoService_GenerateIdentity_Handler,
		},
		{
			MethodName: "ExportIdentity",
			Handler:    _MLSCryptoService_ExportIdentity_Handler,
		},
		{
			MethodName: "ImportIdentity",
			Handler:    _MLSCryptoService_ImportIdentity_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _MLSCryptoService_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mls_service.proto",
}
