// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.6
// source: mls_service.proto

package mls_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message for generating a new identity.
type GenerateIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdentityRequest) Reset() {
	*x = GenerateIdentityRequest{}
	mi := &file_mls_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdentityRequest) ProtoMessage() {}

func (x *GenerateIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdentityRequest.ProtoReflect.Descriptor instead.
func (*GenerateIdentityRequest) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{0}
}

type GenerateIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPackage    []byte                 `protobuf:"bytes,1,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"` // The generated KeyPackage in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateIdentityResponse) Reset() {
	*x = GenerateIdentityResponse{}
	mi := &file_mls_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateIdentityResponse) ProtoMessage() {}

func (x *GenerateIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateIdentityResponse.ProtoReflect.Descriptor instead.
func (*GenerateIdentityResponse) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateIdentityResponse) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

// Message for exporting an identity.
type ExportIdentityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPackage    []byte                 `protobuf:"bytes,1,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"` // The KeyPackage to export
	Passphrase    string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`                   // Passphrase to encrypt the exported data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportIdentityRequest) Reset() {
	*x = ExportIdentityRequest{}
	mi := &file_mls_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportIdentityRequest) ProtoMessage() {}

func (x *ExportIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportIdentityRequest.ProtoReflect.Descriptor instead.
func (*ExportIdentityRequest) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{2}
}

func (x *ExportIdentityRequest) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

func (x *ExportIdentityRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type ExportIdentityResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EncryptedBackupData []byte                 `protobuf:"bytes,1,opt,name=encrypted_backup_data,json=encryptedBackupData,proto3" json:"encrypted_backup_data,omitempty"` // Encrypted identity data
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ExportIdentityResponse) Reset() {
	*x = ExportIdentityResponse{}
	mi := &file_mls_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportIdentityResponse) ProtoMessage() {}

func (x *ExportIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportIdentityResponse.ProtoReflect.Descriptor instead.
func (*ExportIdentityResponse) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{3}
}

func (x *ExportIdentityResponse) GetEncryptedBackupData() []byte {
	if x != nil {
		return x.EncryptedBackupData
	}
	return nil
}

// Message for importing an identity.
type ImportIdentityRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	EncryptedBackupData []byte                 `protobuf:"bytes,1,opt,name=encrypted_backup_data,json=encryptedBackupData,proto3" json:"encrypted_backup_data,omitempty"` // Encrypted identity data
	Passphrase          string                 `protobuf:"bytes,2,opt,name=passphrase,proto3" json:"passphrase,omitempty"`                                                // Passphrase to decrypt the data
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ImportIdentityRequest) Reset() {
	*x = ImportIdentityRequest{}
	mi := &file_mls_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportIdentityRequest) ProtoMessage() {}

func (x *ImportIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportIdentityRequest.ProtoReflect.Descriptor instead.
func (*ImportIdentityRequest) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{4}
}

func (x *ImportIdentityRequest) GetEncryptedBackupData() []byte {
	if x != nil {
		return x.EncryptedBackupData
	}
	return nil
}

func (x *ImportIdentityRequest) GetPassphrase() string {
	if x != nil {
		return x.Passphrase
	}
	return ""
}

type ImportIdentityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyPackage    []byte                 `protobuf:"bytes,1,opt,name=key_package,json=keyPackage,proto3" json:"key_package,omitempty"` // The imported KeyPackage in bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImportIdentityResponse) Reset() {
	*x = ImportIdentityResponse{}
	mi := &file_mls_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImportIdentityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportIdentityResponse) ProtoMessage() {}

func (x *ImportIdentityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportIdentityResponse.ProtoReflect.Descriptor instead.
func (*ImportIdentityResponse) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{5}
}

func (x *ImportIdentityResponse) GetKeyPackage() []byte {
	if x != nil {
		return x.KeyPackage
	}
	return nil
}

// A generic message type for MLS messages (e.g., handshake, application messages).
type MlsMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Raw MLS message bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MlsMessage) Reset() {
	*x = MlsMessage{}
	mi := &file_mls_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MlsMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MlsMessage) ProtoMessage() {}

func (x *MlsMessage) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MlsMessage.ProtoReflect.Descriptor instead.
func (*MlsMessage) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{6}
}

func (x *MlsMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// A message type for KeyPackage (public identity information).
type KeyPackage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // Raw KeyPackage bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyPackage) Reset() {
	*x = KeyPackage{}
	mi := &file_mls_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyPackage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyPackage) ProtoMessage() {}

func (x *KeyPackage) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyPackage.ProtoReflect.Descriptor instead.
func (*KeyPackage) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{7}
}

func (x *KeyPackage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Ping Request and Response
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_mls_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{8}
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_mls_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_mls_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_mls_service_proto_rawDescGZIP(), []int{9}
}

func (x *PingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_mls_service_proto protoreflect.FileDescriptor

const file_mls_service_proto_rawDesc = "" +
	"\n" +
	"\x11mls_service.proto\x12\vmls_service\"\x19\n" +
	"\x17GenerateIdentityRequest\";\n" +
	"\x18GenerateIdentityResponse\x12\x1f\n" +
	"\vkey_package\x18\x01 \x01(\fR\n" +
	"keyPackage\"X\n" +
	"\x15ExportIdentityRequest\x12\x1f\n" +
	"\vkey_package\x18\x01 \x01(\fR\n" +
	"keyPackage\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"L\n" +
	"\x16ExportIdentityResponse\x122\n" +
	"\x15encrypted_backup_data\x18\x01 \x01(\fR\x13encryptedBackupData\"k\n" +
	"\x15ImportIdentityRequest\x122\n" +
	"\x15encrypted_backup_data\x18\x01 \x01(\fR\x13encryptedBackupData\x12\x1e\n" +
	"\n" +
	"passphrase\x18\x02 \x01(\tR\n" +
	"passphrase\"9\n" +
	"\x16ImportIdentityResponse\x12\x1f\n" +
	"\vkey_package\x18\x01 \x01(\fR\n" +
	"keyPackage\" \n" +
	"\n" +
	"MlsMessage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\" \n" +
	"\n" +
	"KeyPackage\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\r\n" +
	"\vPingRequest\"F\n" +
	"\fPingResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp2\xe6\x02\n" +
	"\x10MLSCryptoService\x12_\n" +
	"\x10GenerateIdentity\x12$.mls_service.GenerateIdentityRequest\x1a%.mls_service.GenerateIdentityResponse\x12Y\n" +
	"\x0eExportIdentity\x12\".mls_service.ExportIdentityRequest\x1a#.mls_service.ExportIdentityResponse\x12Y\n" +
	"\x0eImportIdentity\x12\".mls_service.ImportIdentityRequest\x1a#.mls_service.ImportIdentityResponse\x12;\n" +
	"\x04Ping\x12\x18.mls_service.PingRequest\x1a\x19.mls_service.PingResponseB\x15Z\x13backend/mls_serviceb\x06proto3"

var (
	file_mls_service_proto_rawDescOnce sync.Once
	file_mls_service_proto_rawDescData []byte
)

func file_mls_service_proto_rawDescGZIP() []byte {
	file_mls_service_proto_rawDescOnce.Do(func() {
		file_mls_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mls_service_proto_rawDesc), len(file_mls_service_proto_rawDesc)))
	})
	return file_mls_service_proto_rawDescData
}

var file_mls_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_mls_service_proto_goTypes = []any{
	(*GenerateIdentityRequest)(nil),  // 0: mls_service.GenerateIdentityRequest
	(*GenerateIdentityResponse)(nil), // 1: mls_service.GenerateIdentityResponse
	(*ExportIdentityRequest)(nil),    // 2: mls_service.ExportIdentityRequest
	(*ExportIdentityResponse)(nil),   // 3: mls_service.ExportIdentityResponse
	(*ImportIdentityRequest)(nil),    // 4: mls_service.ImportIdentityRequest
	(*ImportIdentityResponse)(nil),   // 5: mls_service.ImportIdentityResponse
	(*MlsMessage)(nil),               // 6: mls_service.MlsMessage
	(*KeyPackage)(nil),               // 7: mls_service.KeyPackage
	(*PingRequest)(nil),              // 8: mls_service.PingRequest
	(*PingResponse)(nil),             // 9: mls_service.PingResponse
}
var file_mls_service_proto_depIdxs = []int32{
	0, // 0: mls_service.MLSCryptoService.GenerateIdentity:input_type -> mls_service.GenerateIdentityRequest
	2, // 1: mls_service.MLSCryptoService.ExportIdentity:input_type -> mls_service.ExportIdentityRequest
	4, // 2: mls_service.MLSCryptoService.ImportIdentity:input_type -> mls_service.ImportIdentityRequest
	8, // 3: mls_service.MLSCryptoService.Ping:input_type -> mls_service.PingRequest
	1, // 4: mls_service.MLSCryptoService.GenerateIdentity:output_type -> mls_service.GenerateIdentityResponse
	3, // 5: mls_service.MLSCryptoService.ExportIdentity:output_type -> mls_service.ExportIdentityResponse
	5, // 6: mls_service.MLSCryptoService.ImportIdentity:output_type -> mls_service.ImportIdentityResponse
	9, // 7: mls_service.MLSCryptoService.Ping:output_type -> mls_service.PingResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_mls_service_proto_init() }
func file_mls_service_proto_init() {
	if File_mls_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mls_service_proto_rawDesc), len(file_mls_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mls_service_proto_goTypes,
		DependencyIndexes: file_mls_service_proto_depIdxs,
		MessageInfos:      file_mls_service_proto_msgTypes,
	}.Build()
	File_mls_service_proto = out.File
	file_mls_service_proto_goTypes = nil
	file_mls_service_proto_depIdxs = nil
}
