package db

import (
	"database/sql"
	"errors"
	"fmt"
	"log/slog"

	_ "modernc.org/sqlite"
)

// Database wraps the SQLite connection.
type Database struct {
	Conn *sql.DB
}

// MLSIdentity holds the local MLS signing identity generated by the Rust engine.
// There is at most ONE row in the mls_identity table (id = 1).
type MLSIdentity struct {
	DisplayName      string
	PublicKey        []byte // raw Ed25519 public key bytes — send to Admin
	SigningKeyPrivate []byte // raw Ed25519 private key bytes — NEVER leave this machine
	Credential       []byte // UTF-8 display_name bytes (Phase 4: proper BasicCredential)
}

// StoredAuthBundle holds the InvitationBundle received from the Admin.
// There is at most ONE row in the auth_bundle table (id = 1).
type StoredAuthBundle struct {
	DisplayName    string
	PeerID         string // Libp2p PeerID — bound in token to prevent replay attacks
	PublicKey      []byte // must match MLSIdentity.PublicKey
	TokenIssuedAt  int64
	TokenExpiresAt int64
	TokenSignature []byte // Admin's Ed25519 signature over the token payload
	BootstrapAddr  string // Libp2p multiaddr of the Admin node — entry point to the network
	RootPublicKey  []byte // Root Admin public key — stored on first import (TOFU)
}

func InitDB(path string) (*Database, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	d := &Database{Conn: db}
	if err := d.createTables(); err != nil {
		return nil, err
	}

	slog.Info("Database initialized", "path", path)
	return d, nil
}

func (d *Database) createTables() error {
	queries := []string{
		// Legacy tables — kept for backward compatibility
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			username TEXT NOT NULL,
			public_key BLOB,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,
		`CREATE TABLE IF NOT EXISTS messages (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id TEXT NOT NULL,
			sender_id TEXT NOT NULL,
			content TEXT,
			mls_message BLOB,
			timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Generic key-value config store.
		// Used for: libp2p_priv_key, admin_root_private_key, etc.
		`CREATE TABLE IF NOT EXISTS system_config (
			key   TEXT PRIMARY KEY,
			value BLOB
		);`,

		// Local MLS signing identity (one row, id = 1).
		// Generated by Rust engine on first launch.
		// signing_key_private MUST never leave this machine.
		`CREATE TABLE IF NOT EXISTS mls_identity (
			id                  INTEGER PRIMARY KEY,
			display_name        TEXT    NOT NULL,
			public_key          BLOB    NOT NULL,
			signing_key_private BLOB    NOT NULL,
			credential          BLOB    NOT NULL,
			created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// InvitationBundle received from the Admin (one row, id = 1).
		// Required before joining the P2P network.
		`CREATE TABLE IF NOT EXISTS auth_bundle (
			id               INTEGER PRIMARY KEY,
			display_name     TEXT    NOT NULL,
			peer_id          TEXT    NOT NULL DEFAULT '',
			public_key       BLOB    NOT NULL,
			token_issued_at  INTEGER NOT NULL,
			token_expires_at INTEGER NOT NULL,
			token_signature  BLOB    NOT NULL,
			bootstrap_addr   TEXT    NOT NULL,
			root_public_key  BLOB    NOT NULL,
			imported_at      DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,
	}

	for _, q := range queries {
		if _, err := d.Conn.Exec(q); err != nil {
			return fmt.Errorf("failed to create table: %w", err)
		}
	}
	return nil
}

func (d *Database) Close() {
	if d.Conn != nil {
		d.Conn.Close()
	}
}

// ── system_config helpers ────────────────────────────────────────────────────

// SetConfig upserts a key-value pair in system_config.
func (d *Database) SetConfig(key string, value []byte) error {
	_, err := d.Conn.Exec(
		"INSERT OR REPLACE INTO system_config (key, value) VALUES (?, ?)",
		key, value,
	)
	if err != nil {
		return fmt.Errorf("SetConfig(%q): %w", key, err)
	}
	return nil
}

// GetConfig retrieves a value from system_config.
// Returns sql.ErrNoRows if the key does not exist.
func (d *Database) GetConfig(key string) ([]byte, error) {
	var value []byte
	err := d.Conn.QueryRow(
		"SELECT value FROM system_config WHERE key = ?", key,
	).Scan(&value)
	if err != nil {
		return nil, err // includes sql.ErrNoRows unwrapped for easy errors.Is checks
	}
	return value, nil
}

// HasConfig returns true if the given key exists in system_config.
func (d *Database) HasConfig(key string) (bool, error) {
	var count int
	err := d.Conn.QueryRow(
		"SELECT COUNT(*) FROM system_config WHERE key = ?", key,
	).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasConfig(%q): %w", key, err)
	}
	return count > 0, nil
}

// ── mls_identity ─────────────────────────────────────────────────────────────

// SaveMLSIdentity persists the local MLS identity (overwrites if exists).
func (d *Database) SaveMLSIdentity(id *MLSIdentity) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO mls_identity
		 (id, display_name, public_key, signing_key_private, credential)
		 VALUES (1, ?, ?, ?, ?)`,
		id.DisplayName, id.PublicKey, id.SigningKeyPrivate, id.Credential,
	)
	if err != nil {
		return fmt.Errorf("SaveMLSIdentity: %w", err)
	}
	return nil
}

// GetMLSIdentity retrieves the local MLS identity.
// Returns sql.ErrNoRows if no identity has been generated yet.
func (d *Database) GetMLSIdentity() (*MLSIdentity, error) {
	var id MLSIdentity
	err := d.Conn.QueryRow(
		`SELECT display_name, public_key, signing_key_private, credential
		 FROM mls_identity WHERE id = 1`,
	).Scan(&id.DisplayName, &id.PublicKey, &id.SigningKeyPrivate, &id.Credential)
	if err != nil {
		return nil, err
	}
	return &id, nil
}

// UpdateMLSDisplayName updates the display_name and credential of the stored MLS identity.
// Called after an InvitationBundle is imported — the Admin-assigned name replaces the
// placeholder that was stored at key generation time.
func (d *Database) UpdateMLSDisplayName(displayName string) error {
	_, err := d.Conn.Exec(
		`UPDATE mls_identity SET display_name = ?, credential = ? WHERE id = 1`,
		displayName, []byte(displayName),
	)
	if err != nil {
		return fmt.Errorf("UpdateMLSDisplayName: %w", err)
	}
	return nil
}

// HasMLSIdentity returns true if a local MLS identity exists.
func (d *Database) HasMLSIdentity() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM mls_identity").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasMLSIdentity: %w", err)
	}
	return count > 0, nil
}

// ── auth_bundle ───────────────────────────────────────────────────────────────

// SaveAuthBundle persists the InvitationBundle from Admin (overwrites if exists).
func (d *Database) SaveAuthBundle(b *StoredAuthBundle) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO auth_bundle
		 (id, display_name, peer_id, public_key, token_issued_at, token_expires_at,
		  token_signature, bootstrap_addr, root_public_key)
		 VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)`,
		b.DisplayName, b.PeerID, b.PublicKey, b.TokenIssuedAt, b.TokenExpiresAt,
		b.TokenSignature, b.BootstrapAddr, b.RootPublicKey,
	)
	if err != nil {
		return fmt.Errorf("SaveAuthBundle: %w", err)
	}
	return nil
}

// GetAuthBundle retrieves the stored InvitationBundle.
// Returns sql.ErrNoRows if no bundle has been imported yet.
func (d *Database) GetAuthBundle() (*StoredAuthBundle, error) {
	var b StoredAuthBundle
	err := d.Conn.QueryRow(
		`SELECT display_name, peer_id, public_key, token_issued_at, token_expires_at,
		        token_signature, bootstrap_addr, root_public_key
		 FROM auth_bundle WHERE id = 1`,
	).Scan(
		&b.DisplayName, &b.PeerID, &b.PublicKey, &b.TokenIssuedAt, &b.TokenExpiresAt,
		&b.TokenSignature, &b.BootstrapAddr, &b.RootPublicKey,
	)
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// HasAuthBundle returns true if an InvitationBundle has been imported.
func (d *Database) HasAuthBundle() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM auth_bundle").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasAuthBundle: %w", err)
	}
	return count > 0, nil
}

// ErrNotFound is a sentinel that callers can check when a record is missing.
// Use errors.Is(err, db.ErrNotFound) after GetMLSIdentity / GetAuthBundle.
var ErrNotFound = sql.ErrNoRows

// IsNotFound is a convenience wrapper around errors.Is(err, sql.ErrNoRows).
func IsNotFound(err error) bool {
	return errors.Is(err, sql.ErrNoRows)
}
