// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemberToGroup(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddMemberToGroup'](arg1, arg2, arg3);
}

export function CreateAndImportSelfBundle(arg1, arg2) {
  return window['go']['main']['App']['CreateAndImportSelfBundle'](arg1, arg2);
}

export function CreateBundle(arg1) {
  return window['go']['main']['App']['CreateBundle'](arg1);
}

export function CreateGroupChat(arg1) {
  return window['go']['main']['App']['CreateGroupChat'](arg1);
}

export function GenerateKeyPackage() {
  return window['go']['main']['App']['GenerateKeyPackage']();
}

export function GenerateKeys() {
  return window['go']['main']['App']['GenerateKeys']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetGroupMembers(arg1) {
  return window['go']['main']['App']['GetGroupMembers'](arg1);
}

export function GetGroupMessages(arg1) {
  return window['go']['main']['App']['GetGroupMessages'](arg1);
}

export function GetGroupStatus(arg1) {
  return window['go']['main']['App']['GetGroupStatus'](arg1);
}

export function GetGroups() {
  return window['go']['main']['App']['GetGroups']();
}

export function GetNodeStatus() {
  return window['go']['main']['App']['GetNodeStatus']();
}

export function GetOnboardingInfo() {
  return window['go']['main']['App']['GetOnboardingInfo']();
}

export function HasAdminKey() {
  return window['go']['main']['App']['HasAdminKey']();
}

export function InitAdminKey(arg1) {
  return window['go']['main']['App']['InitAdminKey'](arg1);
}

export function JoinGroupWithWelcome(arg1, arg2, arg3) {
  return window['go']['main']['App']['JoinGroupWithWelcome'](arg1, arg2, arg3);
}

export function OpenAndImportBundle() {
  return window['go']['main']['App']['OpenAndImportBundle']();
}

export function SendGroupMessage(arg1, arg2) {
  return window['go']['main']['App']['SendGroupMessage'](arg1, arg2);
}
