// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CreateAndImportSelfBundle(arg1:string,arg2:string):Promise<void>;

export function CreateBundle(arg1:main.CreateBundleRequest):Promise<string>;

export function GenerateKeys():Promise<main.OnboardingInfo>;

export function GetAppState():Promise<string>;

export function GetNodeStatus():Promise<main.NodeStatus>;

export function GetOnboardingInfo():Promise<main.OnboardingInfo>;

export function HasAdminKey():Promise<boolean>;

export function InitAdminKey(arg1:string):Promise<void>;

export function OpenAndImportBundle():Promise<void>;
