// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateAndImportSelfBundle(arg1, arg2) {
  return window['go']['main']['App']['CreateAndImportSelfBundle'](arg1, arg2);
}

export function CreateBundle(arg1) {
  return window['go']['main']['App']['CreateBundle'](arg1);
}

export function GenerateKeys() {
  return window['go']['main']['App']['GenerateKeys']();
}

export function GetAppState() {
  return window['go']['main']['App']['GetAppState']();
}

export function GetNodeStatus() {
  return window['go']['main']['App']['GetNodeStatus']();
}

export function GetOnboardingInfo() {
  return window['go']['main']['App']['GetOnboardingInfo']();
}

export function HasAdminKey() {
  return window['go']['main']['App']['HasAdminKey']();
}

export function InitAdminKey(arg1) {
  return window['go']['main']['App']['InitAdminKey'](arg1);
}

export function OpenAndImportBundle() {
  return window['go']['main']['App']['OpenAndImportBundle']();
}
