// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddMemberToGroup(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CreateAndImportSelfBundle(arg1:string,arg2:string):Promise<void>;

export function CreateBundle(arg1:main.CreateBundleRequest):Promise<string>;

export function CreateGroupChat(arg1:string):Promise<void>;

export function GenerateKeyPackage():Promise<main.KeyPackageResult>;

export function GenerateKeys():Promise<main.OnboardingInfo>;

export function GetAppState():Promise<string>;

export function GetGroupMembers(arg1:string):Promise<Array<main.MemberInfo>>;

export function GetGroupMessages(arg1:string):Promise<Array<main.MessageInfo>>;

export function GetGroupStatus(arg1:string):Promise<Record<string, any>>;

export function GetGroups():Promise<Array<main.GroupInfo>>;

export function GetNodeStatus():Promise<main.NodeStatus>;

export function GetOnboardingInfo():Promise<main.OnboardingInfo>;

export function HasAdminKey():Promise<boolean>;

export function InitAdminKey(arg1:string):Promise<void>;

export function JoinGroupWithWelcome(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenAndImportBundle():Promise<void>;

export function SendGroupMessage(arg1:string,arg2:string):Promise<void>;
