import {
  AddMemberToGroup,
  CheckDHTWelcome,
  CreateChannelCategory,
  CreateAndImportSelfBundle,
  CreateBundle,
  CreateBundleFromRequest,
  CreateGroupChat,
  DeleteChannelCategory,
  DeleteLocalMessage,
  DownloadGroupFile,
  ExportDiagnostics,
  ExportDeviceRequestJSON,
  ExportIdentity,
  GenerateJoinCode,
  GenerateKeys,
  GetAdminStatus,
  GetAggregateRevisions,
  GetAppState,
  GetDiagnosticsSnapshot,
  GetGroupMembers,
  GetMessageLimits,
  GetGroupMessages,
  GetGroupPosts,
  GetPostComments,
  GetGroupStatus,
  GetGroups,
  GetNetworkSettings,
  GetNodeStatus,
  GetKnownPeers,
  GetOfflineSyncStatus,
  GetOnboardingInfo,
  GetRuntimeHealth,
  GetRuntimeEventCursor,
  GetRuntimeEventsSince,
  GetSessionStatus,
  GetGroupInvitePolicy,
  InitAdminKey,
  ImportIdentityFromFile,
  InvitePeerToGroup,
  JoinGroupWithWelcome,
  LeaveGroup,
  ListGroupInviteRequests,
  ListIssuanceHistory,
  ListChannelCategories,
  OpenDownloadedFile,
  OpenLogFolder,
  OpenAndImportBundle,
  ParseDeviceRequestJSON,
  AssignChannelCategory,
  PrepareGroupFile,
  PrepareOutgoingFileTransfer,
  ApproveGroupInviteRequest,
  ReconnectP2P,
  RejectGroupInviteRequest,
  RemoveMemberFromGroup,
  RequestGroupInvite,
  RetryGroupInviteRequest,
  RetryMessage,
  SendGroupMessage,
  SendGroupFile,
  SetBootstrapAddress,
  SetGroupInvitePolicy,
  StartDirectMessage,
  SyncInviteRequestFromCreator,
  TriggerOfflineSync,
  ValidateMultiaddr,
  VerifyAdminPassphrase,
} from '../../../wailsjs/go/service/Runtime'

export const runtimeClient = {
  getAppState: GetAppState,
  getRuntimeHealth: GetRuntimeHealth,
  getRuntimeEventCursor: GetRuntimeEventCursor,
  getRuntimeEventsSince: GetRuntimeEventsSince,
  getAggregateRevisions: GetAggregateRevisions,
  getSessionStatus: GetSessionStatus,
  generateKeys: GenerateKeys,
  getOnboardingInfo: GetOnboardingInfo,
  openAndImportBundle: OpenAndImportBundle,
  importIdentityFromFile: ImportIdentityFromFile,
  getNodeStatus: GetNodeStatus,
  getNetworkSettings: GetNetworkSettings,
  validateMultiaddr: ValidateMultiaddr,
  setBootstrapAddress: SetBootstrapAddress,
  reconnectP2P: ReconnectP2P,
  getDiagnosticsSnapshot: GetDiagnosticsSnapshot,
  exportDiagnostics: ExportDiagnostics,
  openLogFolder: OpenLogFolder,
  getOfflineSyncStatus: GetOfflineSyncStatus,
  retryMessage: RetryMessage,
  deleteLocalMessage: DeleteLocalMessage,
  getGroups: GetGroups,
  getKnownPeers: GetKnownPeers,
  getGroupStatus: GetGroupStatus,
  getGroupMembers: GetGroupMembers,
  getMessageLimits: GetMessageLimits,
  getGroupMessages: GetGroupMessages,
  getGroupPosts: GetGroupPosts,
  getPostComments: GetPostComments,
  createGroupChat: CreateGroupChat,
  listChannelCategories: ListChannelCategories,
  createChannelCategory: CreateChannelCategory,
  deleteChannelCategory: DeleteChannelCategory,
  assignChannelCategory: AssignChannelCategory,
  sendGroupMessage: SendGroupMessage,
  sendGroupFile: SendGroupFile,
  prepareGroupFile: PrepareGroupFile,
  prepareOutgoingFileTransfer: PrepareOutgoingFileTransfer,
  downloadGroupFile: DownloadGroupFile,
  openDownloadedFile: OpenDownloadedFile,
  leaveGroup: LeaveGroup,
  removeMemberFromGroup: RemoveMemberFromGroup,
  addMemberToGroup: AddMemberToGroup,
  generateJoinCode: GenerateJoinCode,
  invitePeerToGroup: InvitePeerToGroup,
  requestGroupInvite: RequestGroupInvite,
  listGroupInviteRequests: ListGroupInviteRequests,
  approveGroupInviteRequest: ApproveGroupInviteRequest,
  rejectGroupInviteRequest: RejectGroupInviteRequest,
  retryGroupInviteRequest: RetryGroupInviteRequest,
  setGroupInvitePolicy: SetGroupInvitePolicy,
  getGroupInvitePolicy: async (groupId: string): Promise<'creator_approval' | 'any_member'> => {
    try {
      const p = await GetGroupInvitePolicy(groupId)
      return p === 'any_member' ? 'any_member' : 'creator_approval'
    } catch {
      return 'creator_approval'
    }
  },
  checkDHTWelcome: CheckDHTWelcome,
  joinGroupWithWelcome: JoinGroupWithWelcome,
  triggerOfflineSync: TriggerOfflineSync,
  exportDeviceRequestJson: ExportDeviceRequestJSON,
  exportIdentity: ExportIdentity,
  getAdminStatus: GetAdminStatus,
  verifyAdminPassphrase: VerifyAdminPassphrase,
  initAdminKey: InitAdminKey,
  parseDeviceRequestJson: ParseDeviceRequestJSON,
  createBundle: CreateBundle,
  createBundleFromRequest: CreateBundleFromRequest,
  listIssuanceHistory: ListIssuanceHistory,
  createAndImportSelfBundle: CreateAndImportSelfBundle,
  syncInviteRequestFromCreator: SyncInviteRequestFromCreator,
  startDirectMessage: StartDirectMessage,
}
