import {
  AcceptInvite,
  AddMemberToGroup,
  CheckDHTWelcome,
  CreateAndImportSelfBundle,
  CreateBundle,
  CreateBundleFromRequest,
  CreateGroupChat,
  DeleteLocalMessage,
  DownloadGroupFile,
  ExportDiagnostics,
  ExportDeviceRequestJSON,
  ExportIdentity,
  GenerateJoinCode,
  GenerateKeys,
  GetAdminStatus,
  GetAggregateRevisions,
  GetAppState,
  GetDiagnosticsSnapshot,
  GetGroupMembers,
  GetMessageLimits,
  GetGroupMessages,
  GetGroupPosts,
  GetPostComments,
  GetGroupStatus,
  GetGroups,
  GetNetworkSettings,
  GetNodeStatus,
  GetKnownPeers,
  GetOfflineSyncStatus,
  GetOnboardingInfo,
  GetRuntimeHealth,
  GetRuntimeEventCursor,
  GetRuntimeEventsSince,
  GetSessionStatus,
  InitAdminKey,
  ImportIdentityFromFile,
  InvitePeerToGroup,
  JoinGroupWithWelcome,
  LeaveGroup,
  ListIssuanceHistory,
  ListPendingInvites,
  OpenDownloadedFile,
  OpenLogFolder,
  OpenAndImportBundle,
  ParseDeviceRequestJSON,
  PrepareGroupFile,
  PrepareOutgoingFileTransfer,
  ReconnectP2P,
  RejectInvite,
  RemoveMemberFromGroup,
  RetryMessage,
  SendGroupMessage,
  SendGroupFile,
  SetBootstrapAddress,
  TriggerOfflineSync,
  ValidateMultiaddr,
  VerifyAdminPassphrase,
} from '../../../wailsjs/go/service/Runtime'

export const runtimeClient = {
  getAppState: GetAppState,
  getRuntimeHealth: GetRuntimeHealth,
  getRuntimeEventCursor: GetRuntimeEventCursor,
  getRuntimeEventsSince: GetRuntimeEventsSince,
  getAggregateRevisions: GetAggregateRevisions,
  getSessionStatus: GetSessionStatus,
  generateKeys: GenerateKeys,
  getOnboardingInfo: GetOnboardingInfo,
  openAndImportBundle: OpenAndImportBundle,
  importIdentityFromFile: ImportIdentityFromFile,
  getNodeStatus: GetNodeStatus,
  getNetworkSettings: GetNetworkSettings,
  validateMultiaddr: ValidateMultiaddr,
  setBootstrapAddress: SetBootstrapAddress,
  reconnectP2P: ReconnectP2P,
  getDiagnosticsSnapshot: GetDiagnosticsSnapshot,
  exportDiagnostics: ExportDiagnostics,
  openLogFolder: OpenLogFolder,
  getOfflineSyncStatus: GetOfflineSyncStatus,
  retryMessage: RetryMessage,
  deleteLocalMessage: DeleteLocalMessage,
  getGroups: GetGroups,
  getKnownPeers: GetKnownPeers,
  getGroupStatus: GetGroupStatus,
  getGroupMembers: GetGroupMembers,
  getMessageLimits: GetMessageLimits,
  getGroupMessages: GetGroupMessages,
  getGroupPosts: GetGroupPosts,
  getPostComments: GetPostComments,
  createGroupChat: CreateGroupChat,
  sendGroupMessage: SendGroupMessage,
  sendGroupFile: SendGroupFile,
  prepareGroupFile: PrepareGroupFile,
  prepareOutgoingFileTransfer: PrepareOutgoingFileTransfer,
  downloadGroupFile: DownloadGroupFile,
  openDownloadedFile: OpenDownloadedFile,
  leaveGroup: LeaveGroup,
  removeMemberFromGroup: RemoveMemberFromGroup,
  addMemberToGroup: AddMemberToGroup,
  generateJoinCode: GenerateJoinCode,
  invitePeerToGroup: InvitePeerToGroup,
  checkDHTWelcome: CheckDHTWelcome,
  joinGroupWithWelcome: JoinGroupWithWelcome,
  listPendingInvites: ListPendingInvites,
  acceptInvite: AcceptInvite,
  rejectInvite: RejectInvite,
  triggerOfflineSync: TriggerOfflineSync,
  exportDeviceRequestJson: ExportDeviceRequestJSON,
  exportIdentity: ExportIdentity,
  getAdminStatus: GetAdminStatus,
  verifyAdminPassphrase: VerifyAdminPassphrase,
  initAdminKey: InitAdminKey,
  parseDeviceRequestJson: ParseDeviceRequestJSON,
  createBundle: CreateBundle,
  createBundleFromRequest: CreateBundleFromRequest,
  listIssuanceHistory: ListIssuanceHistory,
  createAndImportSelfBundle: CreateAndImportSelfBundle,
  startDirectMessage: async (peerId: string): Promise<string> => {
    const runtime = (window as unknown as { go?: { service?: { Runtime?: { StartDirectMessage?: (id: string) => Promise<string> } } } }).go
      ?.service?.Runtime
    if (runtime?.StartDirectMessage) {
      return runtime.StartDirectMessage(peerId)
    }
    throw new Error('Runtime.StartDirectMessage is not available in current build.')
  },
}
