import {
  AcceptInvite,
  AddMemberToGroup,
  CheckDHTWelcome,
  CreateAndImportSelfBundle,
  CreateBundleFromRequest,
  CreateGroupChat,
  DeleteLocalMessage,
  ExportDiagnostics,
  ExportIdentity,
  GenerateJoinCode,
  GenerateKeys,
  GetAdminStatus,
  GetAppState,
  GetDiagnosticsSnapshot,
  GetGroupMembers,
  GetGroupMessages,
  GetGroupStatus,
  GetGroups,
  GetNetworkSettings,
  GetNodeStatus,
  GetKnownPeers,
  GetOfflineSyncStatus,
  GetOnboardingInfo,
  GetRuntimeHealth,
  GetSessionStatus,
  InitAdminKey,
  ImportIdentityFromFile,
  InvitePeerToGroup,
  JoinGroupWithWelcome,
  LeaveGroup,
  ListIssuanceHistory,
  ListPendingInvites,
  OpenLogFolder,
  OpenAndImportBundle,
  ParseDeviceRequestJSON,
  ReconnectP2P,
  RejectInvite,
  RemoveMemberFromGroup,
  RetryMessage,
  SendGroupMessage,
  SetBootstrapAddress,
  TriggerOfflineSync,
  ValidateMultiaddr,
} from '../../../wailsjs/go/service/Runtime'

export const runtimeClient = {
  getAppState: GetAppState,
  getRuntimeHealth: GetRuntimeHealth,
  getSessionStatus: GetSessionStatus,
  generateKeys: GenerateKeys,
  getOnboardingInfo: GetOnboardingInfo,
  openAndImportBundle: OpenAndImportBundle,
  importIdentityFromFile: ImportIdentityFromFile,
  getNodeStatus: GetNodeStatus,
  getNetworkSettings: GetNetworkSettings,
  validateMultiaddr: ValidateMultiaddr,
  setBootstrapAddress: SetBootstrapAddress,
  reconnectP2P: ReconnectP2P,
  getDiagnosticsSnapshot: GetDiagnosticsSnapshot,
  exportDiagnostics: ExportDiagnostics,
  openLogFolder: OpenLogFolder,
  getOfflineSyncStatus: GetOfflineSyncStatus,
  retryMessage: RetryMessage,
  deleteLocalMessage: DeleteLocalMessage,
  getGroups: GetGroups,
  getKnownPeers: GetKnownPeers,
  getGroupStatus: GetGroupStatus,
  getGroupMembers: GetGroupMembers,
  getGroupMessages: GetGroupMessages,
  createGroupChat: CreateGroupChat,
  sendGroupMessage: SendGroupMessage,
  leaveGroup: LeaveGroup,
  removeMemberFromGroup: RemoveMemberFromGroup,
  addMemberToGroup: AddMemberToGroup,
  generateJoinCode: GenerateJoinCode,
  invitePeerToGroup: InvitePeerToGroup,
  checkDHTWelcome: CheckDHTWelcome,
  joinGroupWithWelcome: JoinGroupWithWelcome,
  listPendingInvites: ListPendingInvites,
  acceptInvite: AcceptInvite,
  rejectInvite: RejectInvite,
  triggerOfflineSync: TriggerOfflineSync,
  exportIdentity: ExportIdentity,
  getAdminStatus: GetAdminStatus,
  initAdminKey: InitAdminKey,
  parseDeviceRequestJson: ParseDeviceRequestJSON,
  createBundleFromRequest: CreateBundleFromRequest,
  listIssuanceHistory: ListIssuanceHistory,
  createAndImportSelfBundle: CreateAndImportSelfBundle,
}
