package store

import (
	"crypto/sha256"
	"database/sql"
	"encoding/hex"
	"errors"
	"fmt"
	"log/slog"
	"regexp"
	"strings"
	"time"

	_ "modernc.org/sqlite"
)

// Database wraps the SQLite connection.
type Database struct {
	Conn *sql.DB
}

// MLSIdentity holds the local MLS signing identity generated by the Rust engine.
// There is at most ONE row in the mls_identity table (id = 1).
type MLSIdentity struct {
	DisplayName       string
	PublicKey         []byte // raw Ed25519 public key bytes — send to Admin
	SigningKeyPrivate []byte // raw Ed25519 private key bytes — NEVER leave this machine
	Credential        []byte // UTF-8 display_name bytes (Phase 4: proper BasicCredential)
}

// StoredAuthBundle holds the InvitationBundle received from the Admin.
// There is at most ONE row in the auth_bundle table (id = 1).
type StoredAuthBundle struct {
	DisplayName    string
	PeerID         string // Libp2p PeerID — bound in token to prevent replay attacks
	PublicKey      []byte // must match MLSIdentity.PublicKey
	TokenIssuedAt  int64
	TokenExpiresAt int64
	TokenSignature []byte // Admin's Ed25519 signature over the token payload
	BootstrapAddr  string // Libp2p multiaddr of the Admin node — entry point to the network
	RootPublicKey  []byte // Root Admin public key — stored on first import (TOFU)
}

func InitDB(path string) (*Database, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}
	// Keep a single writer connection in-process and wait on busy locks
	// to reduce SQLITE_BUSY under concurrent goroutines.
	db.SetMaxOpenConns(1)
	db.SetMaxIdleConns(1)

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}
	if _, err := db.Exec(`PRAGMA journal_mode=WAL;`); err != nil {
		return nil, fmt.Errorf("set pragma journal_mode=WAL: %w", err)
	}
	if _, err := db.Exec(`PRAGMA busy_timeout=5000;`); err != nil {
		return nil, fmt.Errorf("set pragma busy_timeout: %w", err)
	}
	if _, err := db.Exec(`PRAGMA synchronous=NORMAL;`); err != nil {
		return nil, fmt.Errorf("set pragma synchronous: %w", err)
	}

	d := &Database{Conn: db}
	if err := d.createTables(); err != nil {
		return nil, err
	}

	slog.Info("Database initialized", "path", path)
	return d, nil
}

func (d *Database) createTables() error {
	queries := []string{
		// Legacy tables — kept for backward compatibility
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			username TEXT NOT NULL,
			public_key BLOB,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,
		`CREATE TABLE IF NOT EXISTS messages (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id TEXT NOT NULL,
			sender_id TEXT NOT NULL,
			content TEXT,
			mls_message BLOB,
			timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Generic key-value config store.
		// Used for: libp2p_priv_key, admin_root_private_key, etc.
		`CREATE TABLE IF NOT EXISTS system_config (
			key   TEXT PRIMARY KEY,
			value BLOB
		);`,

		// Local MLS signing identity (one row, id = 1).
		// Generated by Rust engine on first launch.
		// signing_key_private MUST never leave this machine.
		`CREATE TABLE IF NOT EXISTS mls_identity (
			id                  INTEGER PRIMARY KEY,
			display_name        TEXT    NOT NULL,
			public_key          BLOB    NOT NULL,
			signing_key_private BLOB    NOT NULL,
			credential          BLOB    NOT NULL,
			created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// InvitationBundle received from the Admin (one row, id = 1).
		// Required before joining the P2P network.
		`CREATE TABLE IF NOT EXISTS auth_bundle (
			id               INTEGER PRIMARY KEY,
			display_name     TEXT    NOT NULL,
			peer_id          TEXT    NOT NULL DEFAULT '',
			public_key       BLOB    NOT NULL,
			token_issued_at  INTEGER NOT NULL,
			token_expires_at INTEGER NOT NULL,
			token_signature  BLOB    NOT NULL,
			bootstrap_addr   TEXT    NOT NULL,
			root_public_key  BLOB    NOT NULL,
			imported_at      DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 4: MLS group state persisted by the Coordinator.
		`CREATE TABLE IF NOT EXISTS mls_groups (
			group_id         TEXT PRIMARY KEY,
			group_state      BLOB    NOT NULL,
			epoch            INTEGER NOT NULL DEFAULT 0,
			tree_hash        BLOB,
			my_role          TEXT    NOT NULL DEFAULT 'member',
			lifecycle_status TEXT    NOT NULL DEFAULT 'active',
			left_at          INTEGER NOT NULL DEFAULT 0,
			group_type       TEXT    NOT NULL DEFAULT 'channel',
			created_at       DATETIME DEFAULT CURRENT_TIMESTAMP,
			updated_at       DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 4: coordination metadata per group.
		`CREATE TABLE IF NOT EXISTS coordination_state (
			group_id          TEXT PRIMARY KEY,
			active_view       TEXT NOT NULL DEFAULT '[]',
			token_holder      TEXT NOT NULL DEFAULT '',
			last_commit_hash  BLOB,
			last_commit_at    DATETIME,
			pending_proposals TEXT NOT NULL DEFAULT '[]',
			FOREIGN KEY (group_id) REFERENCES mls_groups(group_id)
		);`,

		// Phase 4: decrypted messages stored for UI display, ordered by HLC.
		`CREATE TABLE IF NOT EXISTS stored_messages (
			id               INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id         TEXT    NOT NULL,
			epoch            INTEGER NOT NULL,
			sender_id        TEXT    NOT NULL,
			content          BLOB    NOT NULL,
			hlc_wall_time_ms INTEGER NOT NULL,
			hlc_counter      INTEGER NOT NULL,
			hlc_node_id      TEXT    NOT NULL,
			envelope_hash    BLOB
		);`,

		`CREATE INDEX IF NOT EXISTS idx_stored_messages_group_hlc
			ON stored_messages(group_id, hlc_wall_time_ms, hlc_counter, hlc_node_id);`,

		`CREATE INDEX IF NOT EXISTS idx_stored_messages_type
			ON stored_messages(json_extract(content, '$.type')) WHERE json_valid(content);`,
		`CREATE INDEX IF NOT EXISTS idx_stored_messages_post_id
			ON stored_messages(json_extract(content, '$.post_id')) WHERE json_valid(content);`,

		// Phase 7: Local directory caching PeerID -> Display Name.
		`CREATE TABLE IF NOT EXISTS peer_directory (
			peer_id      TEXT PRIMARY KEY,
			display_name TEXT NOT NULL,
			updated_at   DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,
		`CREATE TABLE IF NOT EXISTS group_members (
			group_id      TEXT    NOT NULL,
			peer_id       TEXT    NOT NULL,
			display_name  TEXT    NOT NULL DEFAULT '',
			role          TEXT    NOT NULL DEFAULT 'member',
			status        TEXT    NOT NULL DEFAULT 'active',
			source        TEXT    NOT NULL DEFAULT '',
			joined_at     INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			left_at       INTEGER NOT NULL DEFAULT 0,
			updated_at    INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (group_id, peer_id)
		);`,
		`CREATE INDEX IF NOT EXISTS idx_group_members_group_status
			ON group_members(group_id, status);`,
		`CREATE INDEX IF NOT EXISTS idx_group_members_peer
			ON group_members(peer_id);`,

		// Phase 5: local KeyPackage private bundles (one active per peer; reused after group join).
		// public_kp is used for invite distribution; private_bundle stays local forever.
		`CREATE TABLE IF NOT EXISTS kp_bundles (
			id              INTEGER PRIMARY KEY,
			peer_id         TEXT    NOT NULL UNIQUE,
			public_kp       BLOB    NOT NULL,
			private_bundle  BLOB    NOT NULL,
			created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 5: outbound Welcome messages awaiting delivery (store-and-forward).
		// Creator side: written after AddMembers, deleted when invitee confirms join.
		`CREATE TABLE IF NOT EXISTS pending_welcomes_out (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			target_peer_id  TEXT    NOT NULL,
			group_id        TEXT    NOT NULL,
			welcome_bytes   BLOB    NOT NULL,
			delivered       INTEGER NOT NULL DEFAULT 0,
			created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
			UNIQUE(target_peer_id, group_id)
		);`,

		// Phase 5.3: offline sync — MLS ciphertext envelopes (per-node monotonic seq).
		`CREATE TABLE IF NOT EXISTS envelope_log (
			id           INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id     TEXT    NOT NULL,
			seq          INTEGER NOT NULL,
			msg_type     TEXT    NOT NULL,
			epoch        INTEGER NOT NULL,
			envelope     BLOB    NOT NULL,
			hlc_wall_ms  INTEGER NOT NULL,
			hlc_counter  INTEGER NOT NULL,
			hlc_node_id  TEXT    NOT NULL,
			created_at   INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			UNIQUE(group_id, seq)
		);`,
		`CREATE INDEX IF NOT EXISTS idx_envelope_log_group_seq
			ON envelope_log(group_id, seq);`,
		`CREATE TABLE IF NOT EXISTS envelope_dedup (
			group_id      TEXT    NOT NULL,
			envelope_hash BLOB    NOT NULL,
			created_at    INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (group_id, envelope_hash)
		);`,
		`CREATE TABLE IF NOT EXISTS applied_envelopes (
			group_id      TEXT    NOT NULL,
			envelope_hash BLOB    NOT NULL,
			msg_type      TEXT    NOT NULL,
			epoch         INTEGER NOT NULL,
			applied_at    INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (group_id, envelope_hash)
		);`,

		`CREATE TABLE IF NOT EXISTS sync_acks (
			peer_id   TEXT    NOT NULL,
			group_id  TEXT    NOT NULL,
			acked_seq INTEGER NOT NULL DEFAULT 0,
			acked_at  INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (peer_id, group_id)
		);`,

		`CREATE TABLE IF NOT EXISTS pending_delivery_acks (
			id             INTEGER PRIMARY KEY AUTOINCREMENT,
			target_peer_id TEXT    NOT NULL,
			group_id       TEXT    NOT NULL,
			acked_seq      INTEGER NOT NULL,
			created_at     INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			UNIQUE(target_peer_id, group_id)
		);`,

		`CREATE TABLE IF NOT EXISTS offline_sync_pull_state (
			group_id         TEXT NOT NULL,
			remote_peer_id   TEXT NOT NULL,
			last_remote_seq  INTEGER NOT NULL DEFAULT 0,
			updated_at       INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (group_id, remote_peer_id)
		);`,

		// Replicated invite assets stored by online peers (custom store protocol).
		`CREATE TABLE IF NOT EXISTS stored_keypackages (
			peer_id        TEXT PRIMARY KEY,
			public_kp      BLOB NOT NULL,
			source_peer_id TEXT NOT NULL,
			updated_at     INTEGER NOT NULL DEFAULT (strftime('%s','now'))
		);`,
		`CREATE TABLE IF NOT EXISTS stored_welcomes (
			invitee_peer_id TEXT NOT NULL,
			group_id        TEXT NOT NULL,
			group_type      TEXT NOT NULL DEFAULT 'channel',
			welcome_bytes   BLOB NOT NULL,
			source_peer_id  TEXT NOT NULL,
			created_at      INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (invitee_peer_id, group_id)
		);`,

		// Phase 6: invitee-side pending invite lifecycle for product UI.
		// stored_welcomes is replica storage; this table is local UI state.
		`CREATE TABLE IF NOT EXISTS pending_invites (
			id              TEXT PRIMARY KEY,
			group_id        TEXT NOT NULL,
			group_type      TEXT NOT NULL DEFAULT 'channel',
			group_name      TEXT NOT NULL DEFAULT '',
			inviter_peer_id TEXT NOT NULL DEFAULT '',
			welcome_hash    BLOB NOT NULL,
			welcome_bytes   BLOB NOT NULL,
			source_peer_id  TEXT NOT NULL DEFAULT '',
			status          TEXT NOT NULL DEFAULT 'pending',
			received_at     INTEGER NOT NULL,
			updated_at      INTEGER NOT NULL,
			UNIQUE(group_id, welcome_hash)
		);`,
		`CREATE INDEX IF NOT EXISTS idx_pending_invites_status_received
			ON pending_invites(status, received_at);`,
		`CREATE TABLE IF NOT EXISTS admin_issuance_history (
			id             TEXT PRIMARY KEY,
			display_name   TEXT NOT NULL,
			peer_id        TEXT NOT NULL,
			public_key_hex TEXT NOT NULL,
			issued_at      INTEGER NOT NULL,
			expires_at     INTEGER NOT NULL,
			note           TEXT NOT NULL DEFAULT '',
			bundle_path    TEXT NOT NULL DEFAULT ''
		);`,
		`CREATE INDEX IF NOT EXISTS idx_admin_issuance_history_issued_at
			ON admin_issuance_history(issued_at DESC);`,
		`CREATE TABLE IF NOT EXISTS runtime_event_log (
			seq          INTEGER PRIMARY KEY AUTOINCREMENT,
			topic        TEXT    NOT NULL,
			aggregate    TEXT    NOT NULL,
			aggregate_id TEXT    NOT NULL DEFAULT '',
			revision     INTEGER NOT NULL,
			payload_json BLOB    NOT NULL,
			created_at   INTEGER NOT NULL
		);`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_event_log_seq ON runtime_event_log(seq);`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_event_log_aggregate_rev ON runtime_event_log(aggregate, revision);`,
	}

	for _, q := range queries {
		if _, err := d.Conn.Exec(q); err != nil {
			return fmt.Errorf("failed to create table: %w", err)
		}
	}
	if err := d.ensureColumnExists("stored_messages", "envelope_hash", "BLOB"); err != nil {
		return err
	}
	if err := d.ensureColumnExists("mls_groups", "lifecycle_status", "TEXT NOT NULL DEFAULT 'active'"); err != nil {
		return err
	}
	if err := d.ensureColumnExists("mls_groups", "left_at", "INTEGER NOT NULL DEFAULT 0"); err != nil {
		return err
	}
	if err := d.ensureColumnExists("mls_groups", "group_type", "TEXT NOT NULL DEFAULT 'channel'"); err != nil {
		return err
	}
	if err := d.ensureColumnExists("stored_welcomes", "group_type", "TEXT NOT NULL DEFAULT 'channel'"); err != nil {
		return err
	}
	if err := d.ensureColumnExists("pending_invites", "group_type", "TEXT NOT NULL DEFAULT 'channel'"); err != nil {
		return err
	}
	if _, err := d.Conn.Exec(
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_stored_messages_group_envelope_hash
		 ON stored_messages(group_id, envelope_hash)
		 WHERE envelope_hash IS NOT NULL`,
	); err != nil {
		return fmt.Errorf("create stored_messages envelope_hash index: %w", err)
	}
	return nil
}

func (d *Database) ensureColumnExists(tableName, columnName, columnType string) error {
	rows, err := d.Conn.Query(fmt.Sprintf(`PRAGMA table_info(%s)`, tableName))
	if err != nil {
		return fmt.Errorf("table info %s: %w", tableName, err)
	}
	defer rows.Close()

	for rows.Next() {
		var (
			cid        int
			name       string
			typ        string
			notNull    int
			defaultV   sql.NullString
			primaryKey int
		)
		if err := rows.Scan(&cid, &name, &typ, &notNull, &defaultV, &primaryKey); err != nil {
			return fmt.Errorf("scan table info %s: %w", tableName, err)
		}
		if strings.EqualFold(name, columnName) {
			return nil
		}
	}
	if err := rows.Err(); err != nil {
		return fmt.Errorf("iterate table info %s: %w", tableName, err)
	}

	if _, err := d.Conn.Exec(fmt.Sprintf(`ALTER TABLE %s ADD COLUMN %s %s`, tableName, columnName, columnType)); err != nil {
		return fmt.Errorf("add column %s.%s: %w", tableName, columnName, err)
	}
	return nil
}

func (d *Database) Close() {
	if d.Conn != nil {
		d.Conn.Close()
	}
}

// ── system_config helpers ────────────────────────────────────────────────────

// SetConfig upserts a key-value pair in system_config.
func (d *Database) SetConfig(key string, value []byte) error {
	_, err := d.Conn.Exec(
		"INSERT OR REPLACE INTO system_config (key, value) VALUES (?, ?)",
		key, value,
	)
	if err != nil {
		return fmt.Errorf("SetConfig(%q): %w", key, err)
	}
	return nil
}

// GetConfig retrieves a value from system_config.
// Returns sql.ErrNoRows if the key does not exist.
func (d *Database) GetConfig(key string) ([]byte, error) {
	var value []byte
	err := d.Conn.QueryRow(
		"SELECT value FROM system_config WHERE key = ?", key,
	).Scan(&value)
	if err != nil {
		return nil, err // includes sql.ErrNoRows unwrapped for easy errors.Is checks
	}
	return value, nil
}

// HasConfig returns true if the given key exists in system_config.
func (d *Database) HasConfig(key string) (bool, error) {
	var count int
	err := d.Conn.QueryRow(
		"SELECT COUNT(*) FROM system_config WHERE key = ?", key,
	).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasConfig(%q): %w", key, err)
	}
	return count > 0, nil
}

// DeleteConfig removes a key from system_config. It is not an error if the key
// does not exist.
func (d *Database) DeleteConfig(key string) error {
	_, err := d.Conn.Exec("DELETE FROM system_config WHERE key = ?", key)
	if err != nil {
		return fmt.Errorf("DeleteConfig(%q): %w", key, err)
	}
	return nil
}

// ── mls_identity ─────────────────────────────────────────────────────────────

// SaveMLSIdentity persists the local MLS identity (overwrites if exists).
// credential may be empty at key-generation time (Admin assigns it later via
// UpdateMLSDisplayName). We normalise nil → []byte{} to satisfy the NOT NULL
// constraint; proto3 zero-value bytes fields deserialise as nil in Go.
func (d *Database) SaveMLSIdentity(id *MLSIdentity) error {
	credential := id.Credential
	if credential == nil {
		credential = []byte{}
	}
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO mls_identity
		 (id, display_name, public_key, signing_key_private, credential)
		 VALUES (1, ?, ?, ?, ?)`,
		id.DisplayName, id.PublicKey, id.SigningKeyPrivate, credential,
	)
	if err != nil {
		return fmt.Errorf("SaveMLSIdentity: %w", err)
	}
	return nil
}

// GetMLSIdentity retrieves the local MLS identity.
// Returns sql.ErrNoRows if no identity has been generated yet.
func (d *Database) GetMLSIdentity() (*MLSIdentity, error) {
	var id MLSIdentity
	err := d.Conn.QueryRow(
		`SELECT display_name, public_key, signing_key_private, credential
		 FROM mls_identity WHERE id = 1`,
	).Scan(&id.DisplayName, &id.PublicKey, &id.SigningKeyPrivate, &id.Credential)
	if err != nil {
		return nil, err
	}
	return &id, nil
}

// UpdateMLSDisplayName updates the display_name and credential of the stored MLS identity.
// Called after an InvitationBundle is imported — the Admin-assigned name replaces the
// placeholder that was stored at key generation time.
func (d *Database) UpdateMLSDisplayName(displayName string) error {
	_, err := d.Conn.Exec(
		`UPDATE mls_identity SET display_name = ?, credential = ? WHERE id = 1`,
		displayName, []byte(displayName),
	)
	if err != nil {
		return fmt.Errorf("UpdateMLSDisplayName: %w", err)
	}
	return nil
}

// HasMLSIdentity returns true if a local MLS identity exists.
func (d *Database) HasMLSIdentity() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM mls_identity").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasMLSIdentity: %w", err)
	}
	return count > 0, nil
}

// ── peer_directory ────────────────────────────────────────────────────────────

// SavePeerProfile inserts or updates a peer's display name mapping.
func (d *Database) SavePeerProfile(peerID string, displayName string) error {
	if peerID == "" || displayName == "" {
		return nil
	}
	_, err := d.Conn.Exec(
		`INSERT INTO peer_directory (peer_id, display_name, updated_at)
		 VALUES (?, ?, CURRENT_TIMESTAMP)
		 ON CONFLICT(peer_id) DO UPDATE SET display_name = excluded.display_name, updated_at = CURRENT_TIMESTAMP`,
		peerID, displayName,
	)
	if err != nil {
		return fmt.Errorf("SavePeerProfile: %w", err)
	}
	return nil
}

func (d *Database) UpsertPeerProfile(peerID, displayName string) error {
	return d.SavePeerProfile(peerID, displayName)
}

// GetPeerDisplayName retrieves the display name of a peer, or empty if unknown.
func (d *Database) GetPeerDisplayName(peerID string) (string, error) {
	var name string
	err := d.Conn.QueryRow("SELECT display_name FROM peer_directory WHERE peer_id = ?", peerID).Scan(&name)
	if err != nil {
		if err == sql.ErrNoRows {
			return "", nil
		}
		return "", fmt.Errorf("GetPeerDisplayName: %w", err)
	}
	return name, nil
}

func (d *Database) GetPeerProfile(peerID string) (string, error) {
	return d.GetPeerDisplayName(peerID)
}

// GetAllPeerProfiles returns all cached PeerID -> Display Name mappings.
func (d *Database) GetAllPeerProfiles() (map[string]string, error) {
	rows, err := d.Conn.Query("SELECT peer_id, display_name FROM peer_directory")
	if err != nil {
		return nil, fmt.Errorf("GetAllPeerProfiles: %w", err)
	}
	defer rows.Close()

	out := make(map[string]string)
	for rows.Next() {
		var pid, name string
		if err := rows.Scan(&pid, &name); err != nil {
			return nil, err
		}
		out[pid] = name
	}
	return out, nil
}

func normalizeGroupMemberStatus(status string) string {
	switch strings.TrimSpace(strings.ToLower(status)) {
	case GroupMemberStatusLeft:
		return GroupMemberStatusLeft
	default:
		return GroupMemberStatusActive
	}
}

func normalizeGroupMemberRole(role string) string {
	role = strings.TrimSpace(strings.ToLower(role))
	if role == "" {
		return "member"
	}
	return role
}

func (d *Database) UpsertGroupMember(rec GroupMemberRecord) error {
	rec.GroupID = strings.TrimSpace(rec.GroupID)
	rec.PeerID = strings.TrimSpace(rec.PeerID)
	if rec.GroupID == "" || rec.PeerID == "" {
		return fmt.Errorf("UpsertGroupMember: group_id and peer_id are required")
	}
	rec.Status = normalizeGroupMemberStatus(rec.Status)
	rec.Role = normalizeGroupMemberRole(rec.Role)
	rec.Source = strings.TrimSpace(rec.Source)
	now := time.Now().Unix()
	if rec.JoinedAt <= 0 {
		rec.JoinedAt = now
	}
	if rec.UpdatedAt <= 0 {
		rec.UpdatedAt = now
	}

	_, err := d.Conn.Exec(
		`INSERT INTO group_members (
			group_id, peer_id, display_name, role, status, source, joined_at, left_at, updated_at
		) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
		ON CONFLICT(group_id, peer_id) DO UPDATE SET
			display_name = CASE
				WHEN excluded.display_name != '' THEN excluded.display_name
				ELSE group_members.display_name
			END,
			role = CASE
				WHEN excluded.role != '' THEN excluded.role
				ELSE group_members.role
			END,
			status = excluded.status,
			source = CASE
				WHEN excluded.source != '' THEN excluded.source
				ELSE group_members.source
			END,
			left_at = CASE
				WHEN excluded.left_at > 0 THEN excluded.left_at
				ELSE group_members.left_at
			END,
			joined_at = CASE
				WHEN group_members.joined_at <= 0 THEN excluded.joined_at
				ELSE group_members.joined_at
			END,
			updated_at = excluded.updated_at`,
		rec.GroupID, rec.PeerID, rec.DisplayName, rec.Role, rec.Status, rec.Source, rec.JoinedAt, rec.LeftAt, rec.UpdatedAt,
	)
	if err != nil {
		return fmt.Errorf("UpsertGroupMember: %w", err)
	}
	return nil
}

func (d *Database) ListGroupMembers(groupID string, statuses ...string) ([]GroupMemberRecord, error) {
	groupID = strings.TrimSpace(groupID)
	if groupID == "" {
		return nil, fmt.Errorf("ListGroupMembers: group_id is required")
	}

	query := `SELECT group_id, peer_id, display_name, role, status, source, joined_at, left_at, updated_at
	          FROM group_members
			  WHERE group_id = ?`
	args := []interface{}{groupID}
	if len(statuses) > 0 {
		filtered := make([]string, 0, len(statuses))
		for _, s := range statuses {
			n := normalizeGroupMemberStatus(s)
			if n != "" {
				filtered = append(filtered, n)
			}
		}
		if len(filtered) > 0 {
			holders := make([]string, 0, len(filtered))
			for _, status := range filtered {
				holders = append(holders, "?")
				args = append(args, status)
			}
			query += ` AND status IN (` + strings.Join(holders, ",") + `)`
		}
	}
	query += ` ORDER BY joined_at ASC, peer_id ASC`

	rows, err := d.Conn.Query(query, args...)
	if err != nil {
		return nil, fmt.Errorf("ListGroupMembers: %w", err)
	}
	defer rows.Close()

	out := make([]GroupMemberRecord, 0)
	for rows.Next() {
		var rec GroupMemberRecord
		if err := rows.Scan(&rec.GroupID, &rec.PeerID, &rec.DisplayName, &rec.Role, &rec.Status, &rec.Source, &rec.JoinedAt, &rec.LeftAt, &rec.UpdatedAt); err != nil {
			return nil, fmt.Errorf("ListGroupMembers scan: %w", err)
		}
		rec.Status = normalizeGroupMemberStatus(rec.Status)
		rec.Role = normalizeGroupMemberRole(rec.Role)
		out = append(out, rec)
	}
	return out, rows.Err()
}

func (d *Database) MarkGroupMemberLeft(groupID, peerID string, leftAt int64) error {
	groupID = strings.TrimSpace(groupID)
	peerID = strings.TrimSpace(peerID)
	if groupID == "" || peerID == "" {
		return fmt.Errorf("MarkGroupMemberLeft: group_id and peer_id are required")
	}
	if leftAt <= 0 {
		leftAt = time.Now().Unix()
	}
	res, err := d.Conn.Exec(
		`UPDATE group_members
		 SET status = ?, left_at = ?, updated_at = ?
		 WHERE group_id = ? AND peer_id = ?`,
		GroupMemberStatusLeft, leftAt, time.Now().Unix(), groupID, peerID,
	)
	if err != nil {
		return fmt.Errorf("MarkGroupMemberLeft: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("MarkGroupMemberLeft rows: %w", err)
	}
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (d *Database) UpdateGroupMemberDisplayNameByPeer(peerID, displayName string) error {
	peerID = strings.TrimSpace(peerID)
	displayName = strings.TrimSpace(displayName)
	if peerID == "" || displayName == "" {
		return nil
	}
	_, err := d.Conn.Exec(
		`UPDATE group_members
		 SET display_name = ?, updated_at = ?
		 WHERE peer_id = ?`,
		displayName, time.Now().Unix(), peerID,
	)
	if err != nil {
		return fmt.Errorf("UpdateGroupMemberDisplayNameByPeer: %w", err)
	}
	return nil
}

// ── auth_bundle ───────────────────────────────────────────────────────────────

// SaveAuthBundle persists the InvitationBundle from Admin (overwrites if exists).
func (d *Database) SaveAuthBundle(b *StoredAuthBundle) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO auth_bundle
		 (id, display_name, peer_id, public_key, token_issued_at, token_expires_at,
		  token_signature, bootstrap_addr, root_public_key)
		 VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)`,
		b.DisplayName, b.PeerID, b.PublicKey, b.TokenIssuedAt, b.TokenExpiresAt,
		b.TokenSignature, b.BootstrapAddr, b.RootPublicKey,
	)
	if err != nil {
		return fmt.Errorf("SaveAuthBundle: %w", err)
	}
	return nil
}

// GetAuthBundle retrieves the stored InvitationBundle.
// Returns sql.ErrNoRows if no bundle has been imported yet.
func (d *Database) GetAuthBundle() (*StoredAuthBundle, error) {
	var b StoredAuthBundle
	err := d.Conn.QueryRow(
		`SELECT display_name, peer_id, public_key, token_issued_at, token_expires_at,
		        token_signature, bootstrap_addr, root_public_key
		 FROM auth_bundle WHERE id = 1`,
	).Scan(
		&b.DisplayName, &b.PeerID, &b.PublicKey, &b.TokenIssuedAt, &b.TokenExpiresAt,
		&b.TokenSignature, &b.BootstrapAddr, &b.RootPublicKey,
	)
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// HasAuthBundle returns true if an InvitationBundle has been imported.
func (d *Database) HasAuthBundle() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM auth_bundle").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasAuthBundle: %w", err)
	}
	return count > 0, nil
}

// ErrNotFound is a sentinel that callers can check when a record is missing.
// Use errors.Is(err, db.ErrNotFound) after GetMLSIdentity / GetAuthBundle.
var ErrNotFound = sql.ErrNoRows

// IsNotFound is a convenience wrapper around errors.Is(err, sql.ErrNoRows).
func IsNotFound(err error) bool {
	return errors.Is(err, sql.ErrNoRows)
}

// ── kp_bundles ────────────────────────────────────────────────────────────────

// SaveKPBundle upserts the local KeyPackage (public + private) keyed by peerID.
// There is at most one active KP per peer.  A new call replaces the old one.
func (d *Database) SaveKPBundle(peerID string, publicKP, privateBundle []byte) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO kp_bundles (peer_id, public_kp, private_bundle)
		 VALUES (?, ?, ?)`,
		peerID, publicKP, privateBundle,
	)
	if err != nil {
		return fmt.Errorf("SaveKPBundle: %w", err)
	}
	return nil
}

// GetKPBundle retrieves the stored public KP + private bundle for peerID.
// Returns sql.ErrNoRows if none has been generated yet.
func (d *Database) GetKPBundle(peerID string) (publicKP, privateBundle []byte, err error) {
	err = d.Conn.QueryRow(
		`SELECT public_kp, private_bundle FROM kp_bundles WHERE peer_id = ?`, peerID,
	).Scan(&publicKP, &privateBundle)
	return
}

// ── pending_welcomes_out ──────────────────────────────────────────────────────

// SavePendingWelcome stores a Welcome that needs to be delivered to targetPeerID.
// Overwrites any previous pending welcome for the same (target, group) pair.
func (d *Database) SavePendingWelcome(targetPeerID, groupID string, welcomeBytes []byte) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO pending_welcomes_out
		 (target_peer_id, group_id, welcome_bytes, delivered)
		 VALUES (?, ?, ?, 0)`,
		targetPeerID, groupID, welcomeBytes,
	)
	if err != nil {
		return fmt.Errorf("SavePendingWelcome: %w", err)
	}
	return nil
}

// GetAnyPendingWelcomeForGroup returns the latest stored welcome for a
// (target_peer_id, group_id) pair regardless of delivered flag.
func (d *Database) GetAnyPendingWelcomeForGroup(targetPeerID, groupID string) ([]byte, error) {
	var welcome []byte
	err := d.Conn.QueryRow(
		`SELECT welcome_bytes
		 FROM pending_welcomes_out
		 WHERE target_peer_id = ? AND group_id = ?
		 ORDER BY id DESC
		 LIMIT 1`,
		targetPeerID, groupID,
	).Scan(&welcome)
	if err != nil {
		return nil, err
	}
	if len(welcome) == 0 {
		return nil, sql.ErrNoRows
	}
	return welcome, nil
}

// PendingWelcome is one undelivered Welcome record.
type PendingWelcome struct {
	ID           int64
	TargetPeerID string
	GroupID      string
	WelcomeBytes []byte
}

// GetPendingWelcomesFor returns all undelivered Welcomes for the given peer.
func (d *Database) GetPendingWelcomesFor(targetPeerID string) ([]PendingWelcome, error) {
	rows, err := d.Conn.Query(
		`SELECT id, target_peer_id, group_id, welcome_bytes
		 FROM pending_welcomes_out
		 WHERE target_peer_id = ? AND delivered = 0`,
		targetPeerID,
	)
	if err != nil {
		return nil, fmt.Errorf("GetPendingWelcomesFor: %w", err)
	}
	defer rows.Close()

	var out []PendingWelcome
	for rows.Next() {
		var pw PendingWelcome
		if err := rows.Scan(&pw.ID, &pw.TargetPeerID, &pw.GroupID, &pw.WelcomeBytes); err != nil {
			return nil, err
		}
		out = append(out, pw)
	}
	return out, rows.Err()
}

// MarkWelcomeDelivered marks a pending welcome row as delivered.
func (d *Database) MarkWelcomeDelivered(id int64) error {
	_, err := d.Conn.Exec(
		`UPDATE pending_welcomes_out SET delivered = 1 WHERE id = ?`, id,
	)
	return err
}

// SaveStoredKeyPackage upserts a public KeyPackage replica for peerID.
func (d *Database) SaveStoredKeyPackage(peerID string, publicKP []byte, sourcePeerID string) error {
	_, err := d.Conn.Exec(
		`INSERT INTO stored_keypackages (peer_id, public_kp, source_peer_id, updated_at)
		 VALUES (?, ?, ?, strftime('%s','now'))
		 ON CONFLICT(peer_id) DO UPDATE SET
		   public_kp = excluded.public_kp,
		   source_peer_id = excluded.source_peer_id,
		   updated_at = excluded.updated_at`,
		peerID, publicKP, sourcePeerID,
	)
	if err != nil {
		return fmt.Errorf("SaveStoredKeyPackage: %w", err)
	}
	return nil
}

// SaveStoredKeyPackageIfNewer upserts only when publishedAt is newer.
func (d *Database) SaveStoredKeyPackageIfNewer(peerID string, publicKP []byte, sourcePeerID string, publishedAt int64) error {
	_, err := d.Conn.Exec(
		`INSERT INTO stored_keypackages (peer_id, public_kp, source_peer_id, updated_at)
		 VALUES (?, ?, ?, ?)
		 ON CONFLICT(peer_id) DO UPDATE SET
		   public_kp = CASE WHEN excluded.updated_at >= stored_keypackages.updated_at THEN excluded.public_kp ELSE stored_keypackages.public_kp END,
		   source_peer_id = CASE WHEN excluded.updated_at >= stored_keypackages.updated_at THEN excluded.source_peer_id ELSE stored_keypackages.source_peer_id END,
		   updated_at = CASE WHEN excluded.updated_at >= stored_keypackages.updated_at THEN excluded.updated_at ELSE stored_keypackages.updated_at END`,
		peerID, publicKP, sourcePeerID, publishedAt,
	)
	if err != nil {
		return fmt.Errorf("SaveStoredKeyPackageIfNewer: %w", err)
	}
	return nil
}

// GetStoredKeyPackage fetches a replicated public KeyPackage for peerID.
func (d *Database) GetStoredKeyPackage(peerID string) ([]byte, error) {
	var kp []byte
	if err := d.Conn.QueryRow(
		`SELECT public_kp FROM stored_keypackages WHERE peer_id = ?`, peerID,
	).Scan(&kp); err != nil {
		return nil, err
	}
	return kp, nil
}

// SaveStoredWelcome upserts a replicated Welcome for (invitee, group).
func (d *Database) SaveStoredWelcome(inviteePeerID, groupID, groupType string, welcome []byte, sourcePeerID string) error {
	groupType = normalizeGroupType(groupType)
	_, err := d.Conn.Exec(
		`INSERT INTO stored_welcomes (invitee_peer_id, group_id, group_type, welcome_bytes, source_peer_id, created_at)
		 VALUES (?, ?, ?, ?, ?, strftime('%s','now'))
		 ON CONFLICT(invitee_peer_id, group_id) DO UPDATE SET
		   group_type = excluded.group_type,
		   welcome_bytes = excluded.welcome_bytes,
		   source_peer_id = excluded.source_peer_id,
		   created_at = excluded.created_at`,
		inviteePeerID, groupID, groupType, welcome, sourcePeerID,
	)
	if err != nil {
		return fmt.Errorf("SaveStoredWelcome: %w", err)
	}
	return nil
}

// SaveStoredWelcomeIfNewer upserts only when publishedAt is newer.
func (d *Database) SaveStoredWelcomeIfNewer(inviteePeerID, groupID, groupType string, welcome []byte, sourcePeerID string, publishedAt int64) error {
	groupType = normalizeGroupType(groupType)
	_, err := d.Conn.Exec(
		`INSERT INTO stored_welcomes (invitee_peer_id, group_id, group_type, welcome_bytes, source_peer_id, created_at)
		 VALUES (?, ?, ?, ?, ?, ?)
		 ON CONFLICT(invitee_peer_id, group_id) DO UPDATE SET
		   group_type = CASE WHEN excluded.created_at >= stored_welcomes.created_at THEN excluded.group_type ELSE stored_welcomes.group_type END,
		   welcome_bytes = CASE WHEN excluded.created_at >= stored_welcomes.created_at THEN excluded.welcome_bytes ELSE stored_welcomes.welcome_bytes END,
		   source_peer_id = CASE WHEN excluded.created_at >= stored_welcomes.created_at THEN excluded.source_peer_id ELSE stored_welcomes.source_peer_id END,
		   created_at = CASE WHEN excluded.created_at >= stored_welcomes.created_at THEN excluded.created_at ELSE stored_welcomes.created_at END`,
		inviteePeerID, groupID, groupType, welcome, sourcePeerID, publishedAt,
	)
	if err != nil {
		return fmt.Errorf("SaveStoredWelcomeIfNewer: %w", err)
	}
	return nil
}

// DeleteStoredWelcome removes a stored welcome replica for an invitee+group pair.
func (d *Database) DeleteStoredWelcome(inviteePeerID, groupID string) error {
	res, err := d.Conn.Exec(
		`DELETE FROM stored_welcomes WHERE invitee_peer_id = ? AND group_id = ?`,
		inviteePeerID, groupID,
	)
	if err != nil {
		return fmt.Errorf("DeleteStoredWelcome: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("DeleteStoredWelcome rows: %w", err)
	}
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

// GetStoredWelcome fetches a replicated Welcome for (invitee, group).
func (d *Database) GetStoredWelcome(inviteePeerID, groupID string) ([]byte, string, error) {
	var wb []byte
	var groupType string
	if err := d.Conn.QueryRow(
		`SELECT welcome_bytes, group_type FROM stored_welcomes WHERE invitee_peer_id = ? AND group_id = ?`,
		inviteePeerID, groupID,
	).Scan(&wb, &groupType); err != nil {
		return nil, "", err
	}
	return wb, normalizeGroupType(groupType), nil
}

// StoredWelcome is one replicated Welcome object retained locally.
type StoredWelcome struct {
	InviteePeerID string
	GroupID       string
	GroupType     string
	WelcomeBytes  []byte
	SourcePeerID  string
	CreatedAt     int64
}

// ListStoredWelcomesFor returns all stored Welcome replicas for an invitee.
func (d *Database) ListStoredWelcomesFor(inviteePeerID string) ([]StoredWelcome, error) {
	rows, err := d.Conn.Query(
		`SELECT invitee_peer_id, group_id, group_type, welcome_bytes, source_peer_id, created_at
		 FROM stored_welcomes
		 WHERE invitee_peer_id = ?
		 ORDER BY created_at DESC`,
		inviteePeerID,
	)
	if err != nil {
		return nil, fmt.Errorf("ListStoredWelcomesFor: %w", err)
	}
	defer rows.Close()

	var out []StoredWelcome
	for rows.Next() {
		var rec StoredWelcome
		if err := rows.Scan(&rec.InviteePeerID, &rec.GroupID, &rec.GroupType, &rec.WelcomeBytes, &rec.SourcePeerID, &rec.CreatedAt); err != nil {
			return nil, fmt.Errorf("ListStoredWelcomesFor scan: %w", err)
		}
		rec.GroupType = normalizeGroupType(rec.GroupType)
		out = append(out, rec)
	}
	return out, rows.Err()
}

const (
	PendingInviteStatusPending  = "pending"
	PendingInviteStatusAccepted = "accepted"
	PendingInviteStatusRejected = "rejected"
	PendingInviteStatusInvalid  = "invalid"
	PendingInviteStatusExpired  = "expired"
)

func normalizeGroupType(groupType string) string {
	switch strings.TrimSpace(groupType) {
	case "dm":
		return "dm"
	case "group":
		return "group"
	case "channel":
		return "channel"
	default:
		return "channel"
	}
}

// PendingInvite is an invitee-side pending Welcome lifecycle row.
type PendingInvite struct {
	ID            string
	GroupID       string
	GroupType     string
	GroupName     string
	InviterPeerID string
	WelcomeHash   []byte
	WelcomeBytes  []byte
	SourcePeerID  string
	Status        string
	ReceivedAt    int64
	UpdatedAt     int64
}

// PendingInviteID deterministically identifies one Welcome for one group.
func PendingInviteID(groupID string, welcomeBytes []byte) string {
	h := sha256.New()
	h.Write([]byte(groupID))
	h.Write([]byte{0})
	h.Write(welcomeBytes)
	return hex.EncodeToString(h.Sum(nil))
}

func pendingInviteHash(welcomeBytes []byte) []byte {
	sum := sha256.Sum256(welcomeBytes)
	return sum[:]
}

// SavePendingInvite upserts a local pending invite without overwriting terminal states.
func (d *Database) SavePendingInvite(inv *PendingInvite) error {
	if inv == nil {
		return fmt.Errorf("SavePendingInvite: invite is nil")
	}
	if strings.TrimSpace(inv.GroupID) == "" {
		return fmt.Errorf("SavePendingInvite: group_id is required")
	}
	if len(inv.WelcomeBytes) == 0 {
		return fmt.Errorf("SavePendingInvite: welcome_bytes is required")
	}
	now := time.Now().Unix()
	id := strings.TrimSpace(inv.ID)
	if id == "" {
		id = PendingInviteID(inv.GroupID, inv.WelcomeBytes)
	}
	status := strings.TrimSpace(inv.Status)
	if status == "" {
		status = PendingInviteStatusPending
	}
	receivedAt := inv.ReceivedAt
	if receivedAt == 0 {
		receivedAt = now
	}
	welcomeHash := append([]byte(nil), inv.WelcomeHash...)
	if len(welcomeHash) == 0 {
		welcomeHash = pendingInviteHash(inv.WelcomeBytes)
	}

	_, err := d.Conn.Exec(
		`INSERT INTO pending_invites
		 (id, group_id, group_type, group_name, inviter_peer_id, welcome_hash, welcome_bytes, source_peer_id, status, received_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
		 ON CONFLICT(group_id, welcome_hash) DO UPDATE SET
		   group_type = CASE
		     WHEN excluded.group_type IN ('channel', 'group', 'dm') THEN excluded.group_type
		     ELSE pending_invites.group_type
		   END,
		   group_name = CASE
		     WHEN pending_invites.group_name = '' THEN excluded.group_name
		     ELSE pending_invites.group_name
		   END,
		   inviter_peer_id = CASE
		     WHEN pending_invites.inviter_peer_id = '' THEN excluded.inviter_peer_id
		     ELSE pending_invites.inviter_peer_id
		   END,
		   welcome_bytes = excluded.welcome_bytes,
		   source_peer_id = CASE
		     WHEN excluded.source_peer_id != '' THEN excluded.source_peer_id
		     ELSE pending_invites.source_peer_id
		   END,
		   status = CASE
		     WHEN pending_invites.status IN ('accepted', 'rejected') THEN pending_invites.status
		     ELSE excluded.status
		   END,
		   updated_at = excluded.updated_at`,
		id,
		inv.GroupID,
		normalizeGroupType(inv.GroupType),
		inv.GroupName,
		inv.InviterPeerID,
		welcomeHash,
		inv.WelcomeBytes,
		inv.SourcePeerID,
		status,
		receivedAt,
		now,
	)
	if err != nil {
		return fmt.Errorf("SavePendingInvite: %w", err)
	}
	return nil
}

// ListPendingInvites returns local invite rows ordered newest first.
func (d *Database) ListPendingInvites(includeTerminal bool) ([]PendingInvite, error) {
	query := `SELECT id, group_id, group_type, group_name, inviter_peer_id, welcome_hash, welcome_bytes, source_peer_id, status, received_at, updated_at
	          FROM pending_invites`
	if !includeTerminal {
		query += ` WHERE status = 'pending'`
	}
	query += ` ORDER BY received_at DESC, updated_at DESC`

	rows, err := d.Conn.Query(query)
	if err != nil {
		return nil, fmt.Errorf("ListPendingInvites: %w", err)
	}
	defer rows.Close()

	var out []PendingInvite
	for rows.Next() {
		var inv PendingInvite
		if err := rows.Scan(
			&inv.ID,
			&inv.GroupID,
			&inv.GroupType,
			&inv.GroupName,
			&inv.InviterPeerID,
			&inv.WelcomeHash,
			&inv.WelcomeBytes,
			&inv.SourcePeerID,
			&inv.Status,
			&inv.ReceivedAt,
			&inv.UpdatedAt,
		); err != nil {
			return nil, fmt.Errorf("ListPendingInvites scan: %w", err)
		}
		inv.GroupType = normalizeGroupType(inv.GroupType)
		out = append(out, inv)
	}
	return out, rows.Err()
}

func (d *Database) GetPendingInvite(id string) (*PendingInvite, error) {
	var inv PendingInvite
	err := d.Conn.QueryRow(
		`SELECT id, group_id, group_type, group_name, inviter_peer_id, welcome_hash, welcome_bytes, source_peer_id, status, received_at, updated_at
		 FROM pending_invites
		 WHERE id = ?`,
		id,
	).Scan(
		&inv.ID,
		&inv.GroupID,
		&inv.GroupType,
		&inv.GroupName,
		&inv.InviterPeerID,
		&inv.WelcomeHash,
		&inv.WelcomeBytes,
		&inv.SourcePeerID,
		&inv.Status,
		&inv.ReceivedAt,
		&inv.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	inv.GroupType = normalizeGroupType(inv.GroupType)
	return &inv, nil
}

func (d *Database) GetLatestPendingInviteByGroup(groupID string) (*PendingInvite, error) {
	groupID = strings.TrimSpace(groupID)
	if groupID == "" {
		return nil, sql.ErrNoRows
	}
	var inv PendingInvite
	err := d.Conn.QueryRow(
		`SELECT id, group_id, group_type, group_name, inviter_peer_id, welcome_hash, welcome_bytes, source_peer_id, status, received_at, updated_at
		 FROM pending_invites
		 WHERE group_id = ?
		 ORDER BY updated_at DESC, received_at DESC
		 LIMIT 1`,
		groupID,
	).Scan(
		&inv.ID,
		&inv.GroupID,
		&inv.GroupType,
		&inv.GroupName,
		&inv.InviterPeerID,
		&inv.WelcomeHash,
		&inv.WelcomeBytes,
		&inv.SourcePeerID,
		&inv.Status,
		&inv.ReceivedAt,
		&inv.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	inv.GroupType = normalizeGroupType(inv.GroupType)
	return &inv, nil
}

func (d *Database) MarkPendingInviteAccepted(id string) error {
	return d.markPendingInviteStatus(id, PendingInviteStatusAccepted)
}

func (d *Database) MarkPendingInviteRejected(id string) error {
	return d.markPendingInviteStatus(id, PendingInviteStatusRejected)
}

func (d *Database) markPendingInviteStatus(id, status string) error {
	res, err := d.Conn.Exec(
		`UPDATE pending_invites
		 SET status = ?, updated_at = ?
		 WHERE id = ?`,
		status,
		time.Now().Unix(),
		id,
	)
	if err != nil {
		return fmt.Errorf("markPendingInviteStatus: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("markPendingInviteStatus rows: %w", err)
	}
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (d *Database) DeletePendingInvite(id string) error {
	res, err := d.Conn.Exec(`DELETE FROM pending_invites WHERE id = ?`, id)
	if err != nil {
		return fmt.Errorf("DeletePendingInvite: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("DeletePendingInvite rows: %w", err)
	}
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (d *Database) ReopenRejectedInvite(inv *PendingInvite) (string, error) {
	if inv == nil {
		return "", fmt.Errorf("ReopenRejectedInvite: invite is nil")
	}
	if strings.TrimSpace(inv.GroupID) == "" || len(inv.WelcomeBytes) == 0 {
		return "", fmt.Errorf("ReopenRejectedInvite: group_id and welcome_bytes are required")
	}
	now := time.Now().Unix()
	welcomeHash := append([]byte(nil), inv.WelcomeHash...)
	if len(welcomeHash) == 0 {
		welcomeHash = pendingInviteHash(inv.WelcomeBytes)
	}
	newID := strings.TrimSpace(inv.ID)
	if newID == "" {
		newID = PendingInviteID(inv.GroupID, inv.WelcomeBytes)
	}
	res, err := d.Conn.Exec(
		`UPDATE pending_invites
		 SET id = ?,
		     group_type = ?,
		     group_name = CASE WHEN ? != '' THEN ? ELSE group_name END,
		     inviter_peer_id = CASE WHEN ? != '' THEN ? ELSE inviter_peer_id END,
		     welcome_hash = ?,
		     welcome_bytes = ?,
		     source_peer_id = CASE WHEN ? != '' THEN ? ELSE source_peer_id END,
		     status = ?,
		     received_at = ?,
		     updated_at = ?
		 WHERE group_id = ? AND status = ?
		   AND updated_at = (
		     SELECT MAX(updated_at) FROM pending_invites WHERE group_id = ? AND status = ?
		   )`,
		newID,
		normalizeGroupType(inv.GroupType),
		strings.TrimSpace(inv.GroupName), strings.TrimSpace(inv.GroupName),
		strings.TrimSpace(inv.InviterPeerID), strings.TrimSpace(inv.InviterPeerID),
		welcomeHash,
		inv.WelcomeBytes,
		strings.TrimSpace(inv.SourcePeerID), strings.TrimSpace(inv.SourcePeerID),
		PendingInviteStatusPending,
		now,
		now,
		strings.TrimSpace(inv.GroupID),
		PendingInviteStatusRejected,
		strings.TrimSpace(inv.GroupID),
		PendingInviteStatusRejected,
	)
	if err != nil {
		return "", fmt.Errorf("ReopenRejectedInvite: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return "", fmt.Errorf("ReopenRejectedInvite rows: %w", err)
	}
	if n == 0 {
		return "", sql.ErrNoRows
	}
	return newID, nil
}

func (d *Database) HasGroup(groupID string) (bool, error) {
	var one int
	err := d.Conn.QueryRow(`SELECT 1 FROM mls_groups WHERE group_id = ?`, groupID).Scan(&one)
	if err == nil {
		return true, nil
	}
	if errors.Is(err, sql.ErrNoRows) {
		return false, nil
	}
	return false, fmt.Errorf("HasGroup(%q): %w", groupID, err)
}

const (
	GroupLifecycleActive = "active"
	GroupLifecycleLeft   = "left"
)

const (
	GroupMemberStatusActive = "active"
	GroupMemberStatusLeft   = "left"
)

type GroupMemberRecord struct {
	GroupID     string
	PeerID      string
	DisplayName string
	Role        string
	Status      string
	Source      string
	JoinedAt    int64
	LeftAt      int64
	UpdatedAt   int64
}

// MarkGroupLeft marks a group as locally left while preserving state/history.
func (d *Database) MarkGroupLeft(groupID string) error {
	exists, err := d.HasGroup(groupID)
	if err != nil {
		return err
	}
	if !exists {
		return sql.ErrNoRows
	}
	_, err = d.Conn.Exec(
		`UPDATE mls_groups
		 SET lifecycle_status = ?, left_at = CASE WHEN left_at = 0 THEN ? ELSE left_at END, updated_at = CURRENT_TIMESTAMP
		 WHERE group_id = ?`,
		GroupLifecycleLeft,
		time.Now().Unix(),
		groupID,
	)
	if err != nil {
		return fmt.Errorf("MarkGroupLeft(%q): %w", groupID, err)
	}
	return nil
}

func (d *Database) IsGroupActive(groupID string) (bool, error) {
	var status string
	err := d.Conn.QueryRow(`SELECT lifecycle_status FROM mls_groups WHERE group_id = ?`, groupID).Scan(&status)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return false, sql.ErrNoRows
		}
		return false, fmt.Errorf("IsGroupActive(%q): %w", groupID, err)
	}
	return status == "" || status == GroupLifecycleActive, nil
}

type StoredMessageRow struct {
	ID      string
	GroupID string
	Content string
}

var canonicalMessageIDRegex = regexp.MustCompile(`^[0-9a-fA-F]{64}$`)

func isCanonicalMessageID(messageID string) bool {
	return canonicalMessageIDRegex.MatchString(strings.TrimSpace(messageID))
}

type AdminIssuanceRecord struct {
	ID           string
	DisplayName  string
	PeerID       string
	PublicKeyHex string
	IssuedAt     int64
	ExpiresAt    int64
	Note         string
	BundlePath   string
}

func (d *Database) GetStoredMessageByID(groupID string, messageID string) (*StoredMessageRow, error) {
	if !isCanonicalMessageID(messageID) {
		return nil, fmt.Errorf("invalid message_id: expected 64-char hex envelope hash")
	}
	var row StoredMessageRow
	var envelopeHash []byte
	err := d.Conn.QueryRow(
		`SELECT group_id, content, envelope_hash
		 FROM stored_messages
		 WHERE group_id = ?
		   AND LOWER(HEX(envelope_hash)) = LOWER(?)
		 LIMIT 1`,
		groupID, messageID,
	).Scan(&row.GroupID, &row.Content, &envelopeHash)
	if err != nil {
		return nil, err
	}
	if len(envelopeHash) == 0 {
		return nil, fmt.Errorf("invalid stored message: missing envelope_hash")
	}
	row.ID = hex.EncodeToString(envelopeHash)
	return &row, nil
}

func (d *Database) DeleteStoredMessageByID(groupID string, messageID string) error {
	if !isCanonicalMessageID(messageID) {
		return fmt.Errorf("invalid message_id: expected 64-char hex envelope hash")
	}
	res, err := d.Conn.Exec(
		`DELETE FROM stored_messages
		 WHERE group_id = ?
		   AND LOWER(HEX(envelope_hash)) = LOWER(?)`,
		groupID, messageID,
	)
	if err != nil {
		return fmt.Errorf("DeleteStoredMessageByID: %w", err)
	}
	n, err := res.RowsAffected()
	if err != nil {
		return fmt.Errorf("DeleteStoredMessageByID rows: %w", err)
	}
	if n == 0 {
		return sql.ErrNoRows
	}
	return nil
}

func (d *Database) SaveAdminIssuanceRecord(rec AdminIssuanceRecord) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO admin_issuance_history
		 (id, display_name, peer_id, public_key_hex, issued_at, expires_at, note, bundle_path)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
		rec.ID, rec.DisplayName, rec.PeerID, rec.PublicKeyHex, rec.IssuedAt, rec.ExpiresAt, rec.Note, rec.BundlePath,
	)
	if err != nil {
		return fmt.Errorf("SaveAdminIssuanceRecord: %w", err)
	}
	return nil
}

func (d *Database) ListAdminIssuanceHistory() ([]AdminIssuanceRecord, error) {
	rows, err := d.Conn.Query(
		`SELECT id, display_name, peer_id, public_key_hex, issued_at, expires_at, note, bundle_path
		 FROM admin_issuance_history
		 ORDER BY issued_at DESC`,
	)
	if err != nil {
		return nil, fmt.Errorf("ListAdminIssuanceHistory: %w", err)
	}
	defer rows.Close()
	out := make([]AdminIssuanceRecord, 0)
	for rows.Next() {
		var rec AdminIssuanceRecord
		if err := rows.Scan(&rec.ID, &rec.DisplayName, &rec.PeerID, &rec.PublicKeyHex, &rec.IssuedAt, &rec.ExpiresAt, &rec.Note, &rec.BundlePath); err != nil {
			return nil, fmt.Errorf("ListAdminIssuanceHistory scan: %w", err)
		}
		out = append(out, rec)
	}
	return out, rows.Err()
}
