package store

import (
	"database/sql"
	"errors"
	"fmt"
	"log/slog"

	_ "modernc.org/sqlite"
)

// Database wraps the SQLite connection.
type Database struct {
	Conn *sql.DB
}

// MLSIdentity holds the local MLS signing identity generated by the Rust engine.
// There is at most ONE row in the mls_identity table (id = 1).
type MLSIdentity struct {
	DisplayName      string
	PublicKey        []byte // raw Ed25519 public key bytes — send to Admin
	SigningKeyPrivate []byte // raw Ed25519 private key bytes — NEVER leave this machine
	Credential       []byte // UTF-8 display_name bytes (Phase 4: proper BasicCredential)
}

// StoredAuthBundle holds the InvitationBundle received from the Admin.
// There is at most ONE row in the auth_bundle table (id = 1).
type StoredAuthBundle struct {
	DisplayName    string
	PeerID         string // Libp2p PeerID — bound in token to prevent replay attacks
	PublicKey      []byte // must match MLSIdentity.PublicKey
	TokenIssuedAt  int64
	TokenExpiresAt int64
	TokenSignature []byte // Admin's Ed25519 signature over the token payload
	BootstrapAddr  string // Libp2p multiaddr of the Admin node — entry point to the network
	RootPublicKey  []byte // Root Admin public key — stored on first import (TOFU)
}

func InitDB(path string) (*Database, error) {
	db, err := sql.Open("sqlite", path)
	if err != nil {
		return nil, fmt.Errorf("failed to open database: %w", err)
	}

	if err := db.Ping(); err != nil {
		return nil, fmt.Errorf("failed to ping database: %w", err)
	}

	d := &Database{Conn: db}
	if err := d.createTables(); err != nil {
		return nil, err
	}

	slog.Info("Database initialized", "path", path)
	return d, nil
}

func (d *Database) createTables() error {
	queries := []string{
		// Legacy tables — kept for backward compatibility
		`CREATE TABLE IF NOT EXISTS users (
			id TEXT PRIMARY KEY,
			username TEXT NOT NULL,
			public_key BLOB,
			created_at DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,
		`CREATE TABLE IF NOT EXISTS messages (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id TEXT NOT NULL,
			sender_id TEXT NOT NULL,
			content TEXT,
			mls_message BLOB,
			timestamp DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Generic key-value config store.
		// Used for: libp2p_priv_key, admin_root_private_key, etc.
		`CREATE TABLE IF NOT EXISTS system_config (
			key   TEXT PRIMARY KEY,
			value BLOB
		);`,

		// Local MLS signing identity (one row, id = 1).
		// Generated by Rust engine on first launch.
		// signing_key_private MUST never leave this machine.
		`CREATE TABLE IF NOT EXISTS mls_identity (
			id                  INTEGER PRIMARY KEY,
			display_name        TEXT    NOT NULL,
			public_key          BLOB    NOT NULL,
			signing_key_private BLOB    NOT NULL,
			credential          BLOB    NOT NULL,
			created_at          DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// InvitationBundle received from the Admin (one row, id = 1).
		// Required before joining the P2P network.
		`CREATE TABLE IF NOT EXISTS auth_bundle (
			id               INTEGER PRIMARY KEY,
			display_name     TEXT    NOT NULL,
			peer_id          TEXT    NOT NULL DEFAULT '',
			public_key       BLOB    NOT NULL,
			token_issued_at  INTEGER NOT NULL,
			token_expires_at INTEGER NOT NULL,
			token_signature  BLOB    NOT NULL,
			bootstrap_addr   TEXT    NOT NULL,
			root_public_key  BLOB    NOT NULL,
			imported_at      DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 4: MLS group state persisted by the Coordinator.
		`CREATE TABLE IF NOT EXISTS mls_groups (
			group_id    TEXT PRIMARY KEY,
			group_state BLOB    NOT NULL,
			epoch       INTEGER NOT NULL DEFAULT 0,
			tree_hash   BLOB,
			my_role     TEXT    NOT NULL DEFAULT 'member',
			created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
			updated_at  DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 4: coordination metadata per group.
		`CREATE TABLE IF NOT EXISTS coordination_state (
			group_id          TEXT PRIMARY KEY,
			active_view       TEXT NOT NULL DEFAULT '[]',
			token_holder      TEXT NOT NULL DEFAULT '',
			last_commit_hash  BLOB,
			last_commit_at    DATETIME,
			pending_proposals TEXT NOT NULL DEFAULT '[]',
			FOREIGN KEY (group_id) REFERENCES mls_groups(group_id)
		);`,

		// Phase 4: decrypted messages stored for UI display, ordered by HLC.
		`CREATE TABLE IF NOT EXISTS stored_messages (
			id               INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id         TEXT    NOT NULL,
			epoch            INTEGER NOT NULL,
			sender_id        TEXT    NOT NULL,
			content          BLOB    NOT NULL,
			hlc_wall_time_ms INTEGER NOT NULL,
			hlc_counter      INTEGER NOT NULL,
			hlc_node_id      TEXT    NOT NULL
		);`,

		`CREATE INDEX IF NOT EXISTS idx_stored_messages_group_hlc
			ON stored_messages(group_id, hlc_wall_time_ms, hlc_counter, hlc_node_id);`,

		// Phase 5: local KeyPackage private bundles (one active per peer; reused after group join).
		// public_kp is the bytes published to DHT; private_bundle stays local forever.
		`CREATE TABLE IF NOT EXISTS kp_bundles (
			id              INTEGER PRIMARY KEY,
			peer_id         TEXT    NOT NULL UNIQUE,
			public_kp       BLOB    NOT NULL,
			private_bundle  BLOB    NOT NULL,
			created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
		);`,

		// Phase 5: outbound Welcome messages awaiting delivery (store-and-forward).
		// Creator side: written after AddMembers, deleted when invitee confirms join.
		`CREATE TABLE IF NOT EXISTS pending_welcomes_out (
			id              INTEGER PRIMARY KEY AUTOINCREMENT,
			target_peer_id  TEXT    NOT NULL,
			group_id        TEXT    NOT NULL,
			welcome_bytes   BLOB    NOT NULL,
			delivered       INTEGER NOT NULL DEFAULT 0,
			created_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
			UNIQUE(target_peer_id, group_id)
		);`,

		// Phase 5.3: offline sync — MLS ciphertext envelopes (per-node monotonic seq).
		`CREATE TABLE IF NOT EXISTS envelope_log (
			id           INTEGER PRIMARY KEY AUTOINCREMENT,
			group_id     TEXT    NOT NULL,
			seq          INTEGER NOT NULL,
			msg_type     TEXT    NOT NULL,
			epoch        INTEGER NOT NULL,
			envelope     BLOB    NOT NULL,
			hlc_wall_ms  INTEGER NOT NULL,
			hlc_counter  INTEGER NOT NULL,
			hlc_node_id  TEXT    NOT NULL,
			created_at   INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			UNIQUE(group_id, seq)
		);`,
		`CREATE INDEX IF NOT EXISTS idx_envelope_log_group_seq
			ON envelope_log(group_id, seq);`,

		`CREATE TABLE IF NOT EXISTS sync_acks (
			peer_id   TEXT    NOT NULL,
			group_id  TEXT    NOT NULL,
			acked_seq INTEGER NOT NULL DEFAULT 0,
			acked_at  INTEGER NOT NULL DEFAULT 0,
			PRIMARY KEY (peer_id, group_id)
		);`,

		`CREATE TABLE IF NOT EXISTS pending_delivery_acks (
			id             INTEGER PRIMARY KEY AUTOINCREMENT,
			target_peer_id TEXT    NOT NULL,
			group_id       TEXT    NOT NULL,
			acked_seq      INTEGER NOT NULL,
			created_at     INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			UNIQUE(target_peer_id, group_id)
		);`,

		`CREATE TABLE IF NOT EXISTS offline_sync_pull_state (
			group_id         TEXT NOT NULL,
			remote_peer_id   TEXT NOT NULL,
			last_remote_seq  INTEGER NOT NULL DEFAULT 0,
			updated_at       INTEGER NOT NULL DEFAULT (strftime('%s','now')),
			PRIMARY KEY (group_id, remote_peer_id)
		);`,
	}

	for _, q := range queries {
		if _, err := d.Conn.Exec(q); err != nil {
			return fmt.Errorf("failed to create table: %w", err)
		}
	}
	return nil
}

func (d *Database) Close() {
	if d.Conn != nil {
		d.Conn.Close()
	}
}

// ── system_config helpers ────────────────────────────────────────────────────

// SetConfig upserts a key-value pair in system_config.
func (d *Database) SetConfig(key string, value []byte) error {
	_, err := d.Conn.Exec(
		"INSERT OR REPLACE INTO system_config (key, value) VALUES (?, ?)",
		key, value,
	)
	if err != nil {
		return fmt.Errorf("SetConfig(%q): %w", key, err)
	}
	return nil
}

// GetConfig retrieves a value from system_config.
// Returns sql.ErrNoRows if the key does not exist.
func (d *Database) GetConfig(key string) ([]byte, error) {
	var value []byte
	err := d.Conn.QueryRow(
		"SELECT value FROM system_config WHERE key = ?", key,
	).Scan(&value)
	if err != nil {
		return nil, err // includes sql.ErrNoRows unwrapped for easy errors.Is checks
	}
	return value, nil
}

// HasConfig returns true if the given key exists in system_config.
func (d *Database) HasConfig(key string) (bool, error) {
	var count int
	err := d.Conn.QueryRow(
		"SELECT COUNT(*) FROM system_config WHERE key = ?", key,
	).Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasConfig(%q): %w", key, err)
	}
	return count > 0, nil
}

// DeleteConfig removes a key from system_config. It is not an error if the key
// does not exist.
func (d *Database) DeleteConfig(key string) error {
	_, err := d.Conn.Exec("DELETE FROM system_config WHERE key = ?", key)
	if err != nil {
		return fmt.Errorf("DeleteConfig(%q): %w", key, err)
	}
	return nil
}

// ── mls_identity ─────────────────────────────────────────────────────────────

// SaveMLSIdentity persists the local MLS identity (overwrites if exists).
// credential may be empty at key-generation time (Admin assigns it later via
// UpdateMLSDisplayName). We normalise nil → []byte{} to satisfy the NOT NULL
// constraint; proto3 zero-value bytes fields deserialise as nil in Go.
func (d *Database) SaveMLSIdentity(id *MLSIdentity) error {
	credential := id.Credential
	if credential == nil {
		credential = []byte{}
	}
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO mls_identity
		 (id, display_name, public_key, signing_key_private, credential)
		 VALUES (1, ?, ?, ?, ?)`,
		id.DisplayName, id.PublicKey, id.SigningKeyPrivate, credential,
	)
	if err != nil {
		return fmt.Errorf("SaveMLSIdentity: %w", err)
	}
	return nil
}

// GetMLSIdentity retrieves the local MLS identity.
// Returns sql.ErrNoRows if no identity has been generated yet.
func (d *Database) GetMLSIdentity() (*MLSIdentity, error) {
	var id MLSIdentity
	err := d.Conn.QueryRow(
		`SELECT display_name, public_key, signing_key_private, credential
		 FROM mls_identity WHERE id = 1`,
	).Scan(&id.DisplayName, &id.PublicKey, &id.SigningKeyPrivate, &id.Credential)
	if err != nil {
		return nil, err
	}
	return &id, nil
}

// UpdateMLSDisplayName updates the display_name and credential of the stored MLS identity.
// Called after an InvitationBundle is imported — the Admin-assigned name replaces the
// placeholder that was stored at key generation time.
func (d *Database) UpdateMLSDisplayName(displayName string) error {
	_, err := d.Conn.Exec(
		`UPDATE mls_identity SET display_name = ?, credential = ? WHERE id = 1`,
		displayName, []byte(displayName),
	)
	if err != nil {
		return fmt.Errorf("UpdateMLSDisplayName: %w", err)
	}
	return nil
}

// HasMLSIdentity returns true if a local MLS identity exists.
func (d *Database) HasMLSIdentity() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM mls_identity").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasMLSIdentity: %w", err)
	}
	return count > 0, nil
}

// ── auth_bundle ───────────────────────────────────────────────────────────────

// SaveAuthBundle persists the InvitationBundle from Admin (overwrites if exists).
func (d *Database) SaveAuthBundle(b *StoredAuthBundle) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO auth_bundle
		 (id, display_name, peer_id, public_key, token_issued_at, token_expires_at,
		  token_signature, bootstrap_addr, root_public_key)
		 VALUES (1, ?, ?, ?, ?, ?, ?, ?, ?)`,
		b.DisplayName, b.PeerID, b.PublicKey, b.TokenIssuedAt, b.TokenExpiresAt,
		b.TokenSignature, b.BootstrapAddr, b.RootPublicKey,
	)
	if err != nil {
		return fmt.Errorf("SaveAuthBundle: %w", err)
	}
	return nil
}

// GetAuthBundle retrieves the stored InvitationBundle.
// Returns sql.ErrNoRows if no bundle has been imported yet.
func (d *Database) GetAuthBundle() (*StoredAuthBundle, error) {
	var b StoredAuthBundle
	err := d.Conn.QueryRow(
		`SELECT display_name, peer_id, public_key, token_issued_at, token_expires_at,
		        token_signature, bootstrap_addr, root_public_key
		 FROM auth_bundle WHERE id = 1`,
	).Scan(
		&b.DisplayName, &b.PeerID, &b.PublicKey, &b.TokenIssuedAt, &b.TokenExpiresAt,
		&b.TokenSignature, &b.BootstrapAddr, &b.RootPublicKey,
	)
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// HasAuthBundle returns true if an InvitationBundle has been imported.
func (d *Database) HasAuthBundle() (bool, error) {
	var count int
	err := d.Conn.QueryRow("SELECT COUNT(*) FROM auth_bundle").Scan(&count)
	if err != nil {
		return false, fmt.Errorf("HasAuthBundle: %w", err)
	}
	return count > 0, nil
}

// ErrNotFound is a sentinel that callers can check when a record is missing.
// Use errors.Is(err, db.ErrNotFound) after GetMLSIdentity / GetAuthBundle.
var ErrNotFound = sql.ErrNoRows

// IsNotFound is a convenience wrapper around errors.Is(err, sql.ErrNoRows).
func IsNotFound(err error) bool {
	return errors.Is(err, sql.ErrNoRows)
}

// ── kp_bundles ────────────────────────────────────────────────────────────────

// SaveKPBundle upserts the local KeyPackage (public + private) keyed by peerID.
// There is at most one active KP per peer.  A new call replaces the old one.
func (d *Database) SaveKPBundle(peerID string, publicKP, privateBundle []byte) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO kp_bundles (peer_id, public_kp, private_bundle)
		 VALUES (?, ?, ?)`,
		peerID, publicKP, privateBundle,
	)
	if err != nil {
		return fmt.Errorf("SaveKPBundle: %w", err)
	}
	return nil
}

// GetKPBundle retrieves the stored public KP + private bundle for peerID.
// Returns sql.ErrNoRows if none has been generated yet.
func (d *Database) GetKPBundle(peerID string) (publicKP, privateBundle []byte, err error) {
	err = d.Conn.QueryRow(
		`SELECT public_kp, private_bundle FROM kp_bundles WHERE peer_id = ?`, peerID,
	).Scan(&publicKP, &privateBundle)
	return
}

// ── pending_welcomes_out ──────────────────────────────────────────────────────

// SavePendingWelcome stores a Welcome that needs to be delivered to targetPeerID.
// Overwrites any previous pending welcome for the same (target, group) pair.
func (d *Database) SavePendingWelcome(targetPeerID, groupID string, welcomeBytes []byte) error {
	_, err := d.Conn.Exec(
		`INSERT OR REPLACE INTO pending_welcomes_out
		 (target_peer_id, group_id, welcome_bytes, delivered)
		 VALUES (?, ?, ?, 0)`,
		targetPeerID, groupID, welcomeBytes,
	)
	if err != nil {
		return fmt.Errorf("SavePendingWelcome: %w", err)
	}
	return nil
}

// PendingWelcome is one undelivered Welcome record.
type PendingWelcome struct {
	ID            int64
	TargetPeerID  string
	GroupID       string
	WelcomeBytes  []byte
}

// GetPendingWelcomesFor returns all undelivered Welcomes for the given peer.
func (d *Database) GetPendingWelcomesFor(targetPeerID string) ([]PendingWelcome, error) {
	rows, err := d.Conn.Query(
		`SELECT id, target_peer_id, group_id, welcome_bytes
		 FROM pending_welcomes_out
		 WHERE target_peer_id = ? AND delivered = 0`,
		targetPeerID,
	)
	if err != nil {
		return nil, fmt.Errorf("GetPendingWelcomesFor: %w", err)
	}
	defer rows.Close()

	var out []PendingWelcome
	for rows.Next() {
		var pw PendingWelcome
		if err := rows.Scan(&pw.ID, &pw.TargetPeerID, &pw.GroupID, &pw.WelcomeBytes); err != nil {
			return nil, err
		}
		out = append(out, pw)
	}
	return out, rows.Err()
}

// MarkWelcomeDelivered marks a pending welcome row as delivered.
func (d *Database) MarkWelcomeDelivered(id int64) error {
	_, err := d.Conn.Exec(
		`UPDATE pending_welcomes_out SET delivered = 1 WHERE id = ?`, id,
	)
	return err
}
